---
title: "01_Wrangling"
format: html
editor: visual
---

```{r}

library(tidyverse)

# pollen_samples is pollen samples from bees (pollen) with the abundance data (survey)

```

```{r Paint_combinations, eval = FALSE}

# first chunk is to make unique paint combinations for the bees

# from Richardson et al. (2021) - https://doi.org/10.1038/s42003-021-02048-7

## This programs produces the largest possible set of colour-location combinations with a maximum given number of overlapping spots (max_common_spots, input by the user in variable max_common_spots)
## The set of colour-location combinations produced is sorted in increasing order of overlap between combinations
## Thus starting from the top of the list will always lead to the optimal set (i.e. the set minimising overlap between combinations) regardless of the number of combinations desired
## The code can be adjusted for any number of colours (variable 'colour_list') and any number of paint locations (variable 'locations')
## (Note that the processing time will scale exponentially with the number of colours and number of locations because of the increasing number of possible combinations)
## The program requires the installation of R libraries 'gtools' and 'Rcpp' and calls the associated cpp function "combination_overlap.cpp", which must be in the same folder as this program

# rm(list=ls())
# 
# library(gtools)
# library(Rcpp)
# Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
# sourceCpp('/Users/faith/Desktop/U Ottawa/PhD Chapter 3/sweat_bee_ecology/Extra/Paint_ID_combination_overlap.cpp')
# 
# 
# 
# ## 1. Define Parameters 
# 
# # list of colours
# colour_list <- c("W", "G", "B", "O", "P") # list of 
# # locations on bee
# locations <- c("Top_L","Top_R","Bottom")
# # max number of identical spot combinations
# max_common_spots <- 2                                        
# # number of random trials to obtain best list. Higher = better chance of obtaining longest possible list buit longer processing time
# nb_rand <- 150
# 
# 
# ## 2. Generate all possible colour combinations, for Nb_colours colours & Nb_locations 
# 
# all_combs <- data.frame(permutations(n=length(colour_list) ,r=length(locations),v=colour_list,repeats.allowed=T), stringsAsFactors = F) ; colnames(all_combs) <- c("Top_L","Top_R","Bottom")
# 
# ## 3. Generate edge list: Nb of location-colours attributes that are identical between each pair of combinations 
# 
# all_comb_list <- list()
# for (col_idx in 1:length(locations)){
#   all_comb_list[[col_idx]] <- as.numeric(match(all_combs[,col_idx],colour_list))
# }
# edge_list <- define_edge_list(all_comb_list, length(locations), choose(nrow(all_combs),2))
# 
# ## 4. Using 1000 randomly chosen starting combinations, generate the list of combinations that have no more than max_common_spots in common
# # The starting node leading to the largest list will then be selected
# # In order to obtain the best possible ordering, repeat the process for decreasing number of common spots, until there is no overlap  
#  
# # initialise objects
# selected_combinations <- 1:nrow(all_combs)
# selected_combination_lists <- vector("list", max_common_spots+1) 
# 
# while(max_common_spots>=0){
#   print(paste("Finding combinations that have no more than",max_common_spots,"spots in common..."))
#   selected_combinations <- sort(subsample_combinations(edge_list,max_common_spots,nb_rand, selected_combinations))
#   selected_combination_lists[[max_common_spots+1]] <- selected_combinations
#   ##Now reduce edge list to only contain those combinations
#   edge_list <- edge_list[which(edge_list$comb_1%in%selected_combinations&edge_list$comb_2%in%selected_combinations),]
#   ## In the first iteration, save reduced edge list as it will be used in the next step
#   if (!exists("reduced_edge_list")){reduced_edge_list <- edge_list}
#   max_common_spots <- max_common_spots-1
# }
# 
# 
# ## 5. Sort the selected combinations from most different to most similar, and write it  
# 
# sorted_combinations <- sort_combinations(selected_combination_lists,reduced_edge_list)
# write.table(data.frame(all_combs[as.numeric(sorted_combinations$sorted_indices),],Mean_overlap=round(1000*as.numeric(sorted_combinations$mean_overlap))/1000,stringsAsFactors = F),file="Data/Paint_ID/Paint_IDs_rewritten.csv",col.names=T,row.names=F,quote=F,append=F)


# how many bees did I mark?
IDs_JAM <- read_csv('Data/Paint_ID/Paint_IDs_JAM.csv')
IDs_KB <- read_csv('Data/Paint_ID/Paint_IDs_KB.csv')
length(unique(IDs_JAM$Bee_ID)) # 82 
length(unique(IDs_KB$Bee_ID)) # 32 
# 114 in total

# I caught 49, so 65 were never recaptured
# 43% recapture for pollen

```

```{r Floral_surveys}

# load in floral survey data
survey <- read_csv('/Users/faith/Desktop/U Ottawa/PhD Chapter 3/sweat_bee_ecology/Data/Pollen_and_Surveys/Floral_surveys.csv')

# make first letter capital
survey$Subtype <- str_replace(survey$Subtype, "^\\w{1}", toupper)
survey$Family <- str_replace(survey$Family, "^\\w{1}", toupper)

# check the unique taxa, any diplucates from spelling erorrs? nothing jumpes out
unique(survey$Subtype)
# take only first word (e.g., ignore "fruiting" because the survey was mid season, so coudlve been fruiting in early season)
survey <- mutate(survey, Subtype = word(Subtype, 1))

# inspect
table(survey$Abundance)
# 'not seen' and 'not seen but abundant' mean that plants were in Janice's list of plants on her property, but I did not see them. Couldve been in the hilled forrest that I tried my best to dredge through 
# keep not seen plants in for now

# first make all numbers
survey <- survey %>% mutate(Abundance_number = ifelse(Abundance == 'rare', 1, 
                                                        ifelse(Abundance == 'uncommon', 2, 
                                                            ifelse(Abundance == 'available', 3, 
                                                                  ifelse(Abundance == 'abundant', 4,
                                                                        ifelse(Abundance == 'extremely abundant', 5, 0 ))))))


# rename abundance column
survey <- survey %>% rename(Abundance_original = Abundance_number)


## Make sure the 50m is included in the 200m

# JAM early survey
JAM_50_early <- survey %>% filter(Site == 'JAM' & Range == '50m' & Season == 'early/mid')
JAM_200_early_v1 <- survey %>% filter(Site == 'JAM' & Range == '200m' & Season == 'early/mid')
# delete duplicates within the 50 and 200m 
# not perfect to order by highest abundance instead of compiling them, but I already compilled them motly in the field (e.g., roses on day X could have been uncommon, then the next day I wrote tham as available because I compilled the current survey with the previous day)
JAM_50_early <- JAM_50_early %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
JAM_200_early_v1 <- JAM_200_early_v1 %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
# what are missing in the 200 from 50?
anti_join(JAM_50_early, JAM_200_early_v1, by = c('Subtype', 'Family'))
# minus one level for each plant in the 50m df because it's being considered in the context of 200 instead of 50. E.g., honeysuckle is uncommon for 50m but rare for 200m. Exccept keep rare and extremly abundanct as is
# I went through the more abundant plants (buttercup, capselle, etc) and decided to keep as 5
JAM_50_early <- JAM_50_early %>% mutate(Abundance_for200_v1 = ifelse(Abundance_original == 1 | Abundance_original == 5, Abundance_original, Abundance_original - 1))
# join together
JAM_200_early <- full_join(JAM_50_early, JAM_200_early_v1)
JAM_200_early <- JAM_200_early %>% mutate(Abundance_for200 = ifelse(is.na(Abundance_for200_v1), Abundance_original, Abundance_for200_v1))
# delete duplicates, keep highest abundance dupe
length(unique(JAM_200_early$Subtype)) # 132 unique
JAM_200_early <- JAM_200_early %>%
  group_by(Subtype) %>%
  slice_max(Abundance_for200, n = 1, with_ties = FALSE) %>%
  ungroup()
# clean up columns
JAM_50_early <- select(JAM_50_early, -Abundance_for200_v1)
JAM_50_early <- JAM_50_early %>% rename(Abundance_for50 = Abundance_original)
JAM_200_early <- select(JAM_200_early, -Abundance_for200_v1, -Abundance_original)

# KB early survey
KB_50_early <- survey %>% filter(Site == 'KB' & Range == '50m' & Season == 'early/mid')
KB_200_early_v1 <- survey %>% filter(Site == 'KB' & Range == '200m' & Season == 'early/mid')
# delete duplicates within the 50 and 200m 
KB_50_early <- KB_50_early %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
KB_200_early_v1 <- KB_200_early_v1 %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
# what are missing in the 200 from 50?
anti_join(KB_50_early, KB_200_early_v1, by = c('Subtype', 'Family'))
KB_50_early <- KB_50_early %>% mutate(Abundance_for200_v1 = ifelse(Abundance_original == 1 | Abundance_original == 5, Abundance_original, Abundance_original - 1))
# join together
KB_200_early <- full_join(KB_50_early, KB_200_early_v1)
KB_200_early <- KB_200_early %>% mutate(Abundance_for200 = ifelse(is.na(Abundance_for200_v1), Abundance_original, Abundance_for200_v1))
# delete duplicates, keep highest abundance dupe
length(unique(KB_200_early$Subtype)) # 61 unique
KB_200_early <- KB_200_early %>%
  group_by(Subtype) %>%
  slice_max(Abundance_for200, n = 1, with_ties = FALSE) %>%
  ungroup()
# clean up columns
KB_50_early <- select(KB_50_early, -Abundance_for200_v1)
KB_50_early <- KB_50_early %>% rename(Abundance_for50 = Abundance_original)
KB_200_early <- select(KB_200_early, -Abundance_for200_v1, -Abundance_original)

# JAM late survey
JAM_50_late <- survey %>% filter(Site == 'JAM' & Range == '50m' & Season == 'late')
JAM_200_late_v1 <- survey %>% filter(Site == 'JAM' & Range == '200m' & Season == 'late')
# delete duplicates within the 50 and 200m 
JAM_50_late <- JAM_50_late %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
JAM_200_late_v1 <- JAM_200_late_v1 %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
# what are missing in the 200 from 50?
anti_join(JAM_50_late, JAM_200_late_v1, by = c('Subtype', 'Family'))
# minus one level for each plant in the 50m df because it's being considered in the context of 200 instead of 50. E.g., honeysuckle is uncommon for 50m but rare for 200m. Exccept keep rare and extremly abundanct as is
# I went through the more abundant plants (buttercup, capselle, etc) and decided to keep as 5
JAM_50_late <- JAM_50_late %>% mutate(Abundance_for200_v1 = ifelse(Abundance_original == 1 | Abundance_original == 5, Abundance_original, Abundance_original - 1))
# join together
JAM_200_late <- full_join(JAM_50_late, JAM_200_late_v1)
JAM_200_late <- JAM_200_late %>% mutate(Abundance_for200 = ifelse(is.na(Abundance_for200_v1), Abundance_original, Abundance_for200_v1))
# delete duplicates, keep highest abundance dupe
length(unique(JAM_200_late$Subtype)) # 120 unique
JAM_200_late <- JAM_200_late %>%
  group_by(Subtype) %>%
  slice_max(Abundance_for200, n = 1, with_ties = FALSE) %>%
  ungroup()
# clean up columns
JAM_50_late <- select(JAM_50_late, -Abundance_for200_v1)
JAM_50_late <- JAM_50_late %>% rename(Abundance_for50 = Abundance_original)
JAM_200_late <- select(JAM_200_late, -Abundance_for200_v1, -Abundance_original)

# KB late survey
KB_50_late <- survey %>% filter(Site == 'KB' & Range == '50m' & Season == 'late')
KB_200_late_v1 <- survey %>% filter(Site == 'KB' & Range == '200m' & Season == 'late')
# delete duplicates within the 50 and 200m 
KB_50_late <- KB_50_late %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
KB_200_late_v1 <- KB_200_late_v1 %>%
  group_by(Subtype) %>%
  slice_max(Abundance_original, n = 1, with_ties = FALSE) %>%
  ungroup()
# what are missing in the 200 from 50?
anti_join(KB_50_late, KB_200_late_v1, by = c('Subtype', 'Family'))
# minus one level for each plant in the 50m df because it's being considered in the context of 200 instead of 50. E.g., honeysuckle is uncommon for 50m but rare for 200m. Exccept keep rare and extremly abundanct as is
# I went through the more abundant plants (buttercup, capselle, etc) and decided to keep as 5
KB_50_late <- KB_50_late %>% mutate(Abundance_for200_v1 = ifelse(Abundance_original == 1 | Abundance_original == 5, Abundance_original, Abundance_original - 1))
# join together
KB_200_late <- full_join(KB_50_late, KB_200_late_v1)
KB_200_late <- KB_200_late %>% mutate(Abundance_for200 = ifelse(is.na(Abundance_for200_v1), Abundance_original, Abundance_for200_v1))
# delete duplicates, keep highest abundance dupe
length(unique(KB_200_late$Subtype)) # 32 unique
KB_200_late <- KB_200_late %>%
  group_by(Subtype) %>%
  slice_max(Abundance_for200, n = 1, with_ties = FALSE) %>%
  ungroup()

# clean up columns
KB_50_late <- select(KB_50_late, -Abundance_for200_v1)
KB_50_late <- KB_50_late %>% rename(Abundance_for50 = Abundance_original)
KB_200_late <- select(KB_200_late, -Abundance_for200_v1, -Abundance_original)
# remove word abundance, now only use numbers 
JAM_50_early <- select(JAM_50_early, -Abundance)
KB_50_early <- select(KB_50_early, -Abundance)
JAM_50_late <- select(JAM_50_late, -Abundance)
KB_50_late <- select(KB_50_late, -Abundance)
JAM_200_early <- select(JAM_200_early, -Abundance)
KB_200_early <- select(KB_200_early, -Abundance)
JAM_200_late <- select(JAM_200_late, -Abundance)
KB_200_late <- select(KB_200_late, -Abundance)


### Abundance for RDA

## make abundance at family-level, compile subtypes within families
# e.g., two subtypes of Caprifoliaceae at level 2 get compiled to level 3

# JAM 50 early 
compiled_JAM_50_early <- JAM_50_early %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for50, na.rm = TRUE),
    Abundance_for50_comp = case_when(
      n() == 1 ~ Abundance_for50,   # if Family appears once, keep Abundance_for50 value
      max_abundance == 5 ~ 5,   # if there are duplicates but it's at the max (5), keep at 5  
      n() == 2 & any(Abundance_for50 == 1) ~ Abundance_for50,  # if there are 2 duplicates and at least one is 1, then keep abundance as is 
      TRUE ~ max_abundance + 1   # if there are duplicates but not at the max, add 1 to the count
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns that make sense now that they're compiled 
compiled_JAM_50_early <- compiled_JAM_50_early %>% select(Site, Season, Family, Abundance_for50_comp)
# remove duplicates based on highest abundance, in case some are still 1
compiled_JAM_50_early <- compiled_JAM_50_early %>%  
  group_by(Family) %>%
  slice_max(Abundance_for50_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# JAM 50 late 
compiled_JAM_50_late <- JAM_50_late %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for50, na.rm = TRUE),
    Abundance_for50_comp = case_when(
      n() == 1 ~ Abundance_for50,   # if Family appears once, keep Abundance_for50 value
      max_abundance == 5 ~ 5,   # if there are duplicates but it's at the max (5), keep at 5
      n() == 2 & any(Abundance_for50 == 1) ~ Abundance_for50,  # if there are 2 duplicates and at least one is 1, then keep abundance as is 
      TRUE ~ max_abundance + 1   # if there are duplicates but not at the max, add 1 to the count
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns that make sense now that they're compiled 
compiled_JAM_50_late <- compiled_JAM_50_late %>% select(Site, Season, Family, Abundance_for50_comp)
# remove duplicates based on highest abundance
compiled_JAM_50_late <- compiled_JAM_50_late %>%  
  group_by(Family) %>%
  slice_max(Abundance_for50_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# KB 50 early
compiled_KB_50_early <- KB_50_early %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for50, na.rm = TRUE),
    Abundance_for50_comp = case_when(
      n() == 1 ~ Abundance_for50, 
      max_abundance == 5 ~ 5,    
      n() == 2 & any(Abundance_for50 == 1) ~ Abundance_for50,  
      TRUE ~ max_abundance + 1  
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns I need
compiled_KB_50_early <- compiled_KB_50_early %>% select(Site, Season, Family, Abundance_for50_comp)
# remove duplicates 
compiled_KB_50_early <- compiled_KB_50_early %>%  
  group_by(Family) %>%
  slice_max(Abundance_for50_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# KB 50 late
compiled_KB_50_late <- KB_50_late %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for50, na.rm = TRUE),
    Abundance_for50_comp = case_when(
      n() == 1 ~ Abundance_for50, 
      max_abundance == 5 ~ 5,    
      n() == 2 & any(Abundance_for50 == 1) ~ Abundance_for50,  
      TRUE ~ max_abundance + 1  
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns I need
compiled_KB_50_late <- compiled_KB_50_late %>% select(Site, Season, Family, Abundance_for50_comp)
# remove duplicates 
compiled_KB_50_late <- compiled_KB_50_late %>%  
  group_by(Family) %>%
  slice_max(Abundance_for50_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# JAM 200 early 
compiled_JAM_200_early <- JAM_200_early %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for200, na.rm = TRUE),
    Abundance_for200_comp = case_when(
      n() == 1 ~ Abundance_for200,   
      max_abundance == 5 ~ 5,   
      n() == 2 & any(Abundance_for200 == 1) ~ Abundance_for200, 
      TRUE ~ max_abundance + 1  
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns that make sense now that they're compiled 
compiled_JAM_200_early <- compiled_JAM_200_early %>% select(Site, Season, Family, Abundance_for200_comp)
# remove duplicates based on highest abundance, in case some are still 1
compiled_JAM_200_early <- compiled_JAM_200_early %>%  
  group_by(Family) %>%
  slice_max(Abundance_for200_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# JAM 200 late 
compiled_JAM_200_late <- JAM_200_late %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for200, na.rm = TRUE),
    Abundance_for200_comp = case_when(
      n() == 1 ~ Abundance_for200,   
      max_abundance == 5 ~ 5,   
      n() == 2 & any(Abundance_for200 == 1) ~ Abundance_for200, 
      TRUE ~ max_abundance + 1  
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns that make sense now that they're compiled 
compiled_JAM_200_late <- compiled_JAM_200_late %>% select(Site, Season, Family, Abundance_for200_comp)
# remove duplicates based on highest abundance, in case some are still 1
compiled_JAM_200_late <- compiled_JAM_200_late %>%  
  group_by(Family) %>%
  slice_max(Abundance_for200_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# KB 200 early 
compiled_KB_200_early <- KB_200_early %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for200, na.rm = TRUE),
    Abundance_for200_comp = case_when(
      n() == 1 ~ Abundance_for200,   
      max_abundance == 5 ~ 5,   
      n() == 2 & any(Abundance_for200 == 1) ~ Abundance_for200, 
      TRUE ~ max_abundance + 1  
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns that make sense now that they're compiled 
compiled_KB_200_early <- compiled_KB_200_early %>% select(Site, Season, Family, Abundance_for200_comp)
# remove duplicates based on highest abundance, in case some are still 1
compiled_KB_200_early <- compiled_KB_200_early %>%  
  group_by(Family) %>%
  slice_max(Abundance_for200_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# KB 200 late 
compiled_KB_200_late <- KB_200_late %>%
  group_by(Family) %>%
  mutate(
    max_abundance = max(Abundance_for200, na.rm = TRUE),
    Abundance_for200_comp = case_when(
      n() == 1 ~ Abundance_for200,   
      max_abundance == 5 ~ 5,   
      n() == 2 & any(Abundance_for200 == 1) ~ Abundance_for200, 
      TRUE ~ max_abundance + 1  
    )
  ) %>%
  ungroup() %>%
  select(-max_abundance)

# take only coumns that make sense now that they're compiled 
compiled_KB_200_late <- compiled_KB_200_late %>% select(Site, Season, Family, Abundance_for200_comp)
# remove duplicates based on highest abundance, in case some are still 1
compiled_KB_200_late <- compiled_KB_200_late %>%  
  group_by(Family) %>%
  slice_max(Abundance_for200_comp, n = 1, with_ties = FALSE) %>%
  ungroup()


# # compile them
# m_50 <- rbind(JAM_50_early, KB_50_early, JAM_50_late, KB_50_late)
# m_200 <- rbind(JAM_200_early, KB_200_early, JAM_200_late, KB_200_late)
# 
# # bind and take columns I need
# m_50 <- m_50 %>% select(-Subsite, -Common_name, -Date, -Range)
# m_200 <- m_200 %>% select(-Subsite, -Common_name, -Date, -Range)
# 


```

```{r Bee_pollen_samples}

## Organizing pollen count dataframe

# after identifying the pollen blindly, now merge the pollen ID and the bee ID files together 
pollen_codes <- read_csv('Data/Pollen_and_Surveys/Pollen_codes.csv')
pollen_samples_ID <- read_csv('Data/Pollen_and_Surveys/Pollen_samples_ID.csv')
pollen_0 <- full_join(pollen_samples_ID, pollen_codes, by = "Slide_code") # join

# reorder columns
pollen_0 = pollen_0 %>% select(Site, Bee_ID, Day, Month, Year, Slide_code, Family, Subtype, Count, Pollen_colour)

# creat date column
pollen_0$Date_pollen <- with(pollen_0, paste(Year, paste0(Month,sep = '-', Day), sep = '-'))
str(pollen_0)
pollen_0$Date_pollen <- as.Date(pollen_0$Date_pollen)
pollen_0 <- pollen_0 %>% select(-Day, -Month, -Year)

# combine ID with site in case the same ID was used for both sites
pollen_0$Bee_ID <- as.character(pollen_0$Bee_ID)
pollen_0$Bee_ID <- paste(pollen_0$Site, pollen_0$Bee_ID, sep = '_') 
table(pollen_0$Bee_ID) # looks good

# look through subtypes, make the most narrow taxa that I want
# if it says 'type x' or 'not specified' then replace with family name 
pollen_0 <- pollen_0 %>%
  mutate(Subtype_v1 = ifelse(
    grepl("Type", Subtype, ignore.case = TRUE), Family, Subtype))
pollen_0 <- pollen_0 %>%
  mutate(Subtype_v2 = ifelse(
    grepl("Not specified", Subtype_v1, ignore.case = TRUE), Family, Subtype_v1))
# replace old subtypes column
pollen_0 <- pollen_0 %>% select(-Subtype, -Subtype_v1)
pollen_0 <- pollen_0 %>% rename(Subtype = Subtype_v2)
pollen_0 <- pollen_0 %>%
  relocate(Subtype, .before = 5)


## Slide J-206 has two types of Asteraceae, so combine into one
# already qualifies for flower constancy so not meaninfully different if we combine or not, but required for NMDS

pollen_0 %>% filter(Slide_code == 'J-206')
# count is 291 + 4
# remove dupe
pollen_0 <- pollen_0 %>% filter(Slide_code != 'J-206' | Count != 4)
# change count value
pollen_0 <- pollen_0 %>% 
  mutate(Count = ifelse(Slide_code == 'J-206' & Family == 'Asteraceae', 295, Count))


# count number of samples for each bee
pollen <- pollen_0 %>%
  group_by(Bee_ID) %>%
  mutate(Num_of_samples = n_distinct(Date_pollen)) %>%
  ungroup()

# make sure each individual has 300 pollen grains
pollen %>% 
  group_by(Bee_ID, Date_pollen) %>%
  summarize(sum(Count))

# remove pollen types with less than 1% (1-3 pollen grains) because it could be from landing on the flower for nectar or contamination from making pollen slides, likely not a bee collecting pollen
pollen <- pollen %>% filter(Count > 3)

# sclae the remaining pollen to 300
pollen <- pollen %>%
  group_by(Slide_code) %>%
  mutate(
    total = sum(Count),
    Count_scaled = round(Count / total * 300)
  ) %>%
  ungroup() %>%
  select(-total)

# replace 'grass' with family name
pollen <- pollen %>% mutate(Subtype = sub("^Grass$", "Gramineae", Subtype))

# number of collected pollen types
pollen <- pollen %>%
  group_by(Bee_ID, Date_pollen) %>%
  mutate(Num_of_subtypes = n_distinct(Subtype)) %>%
  ungroup()

# replace spaces for _
pollen$Subtype <- str_replace_all(pollen$Subtype, " ", "_")
pollen$Family <- str_replace_all(pollen$Family, " ", "_")


# # make summary for descriptive stats
# pollen_summary <- pollen %>%
#   distinct(Bee_ID, Date_pollen, .keep_all = TRUE)
# # keep relevant columns
# pollen_summary <- pollen_summary %>%
#   select(Site, Bee_ID, Date_pollen, Num_of_samples, Num_of_subtypes)
# 
# # average samples per bee
# per_bee <- pollen_summary %>% 
#   group_by(Bee_ID) %>% 
#   slice_max(Num_of_samples, n = 1, with_ties = FALSE) %>%
#   ungroup()
# mean(per_bee$Num_of_samples)
# # 1.69


```

```{r Abundance_and_Samples}

## Match abundance with pollen sample data

# assign mid season floral survey to 2024 pollen samples and late season survey to 2025 pollen samples
# if subtype in bee pollen data has an abundance rank in floral data, use that

# check length of df
length(unique(pollen$Slide_code)) # 83 samples
length(pollen$Slide_code) # 147 rows


### 200 m survey ###

# first, divide up pollen samples for KB and JAM, early and late surveys, for subtype-level observations
pollen_JAM_200_early_sub_v1 <- pollen %>% filter(Site == "JAM" & format(Date_pollen, "%Y") == "2024") # 53 samples
pollen_JAM_200_late_sub_v1 <- pollen %>% filter(Site == "JAM" & format(Date_pollen, "%Y") == "2025") # 20 
pollen_KB_200_early_sub_v1 <- pollen %>% filter(Site == "KB" & format(Date_pollen, "%Y") == "2024") # 9
pollen_KB_200_late_sub_v1 <- pollen %>% filter(Site == "KB" & format(Date_pollen, "%Y") == "2025") # 1

# then left_join with floral survey data to join for subtypes if we know them from the pollen samples
pollen_JAM_200_early_sub <- left_join(pollen_JAM_200_early_sub_v1, JAM_200_early, by = c("Site", "Subtype", 'Family')) 
pollen_JAM_200_late_sub <- left_join(pollen_JAM_200_late_sub_v1, JAM_200_late, by = c("Site", "Subtype", 'Family')) 
pollen_KB_200_early_sub <- left_join(pollen_KB_200_early_sub_v1, KB_200_early, by = c("Site", "Subtype", 'Family')) 
pollen_KB_200_late_sub <- left_join(pollen_KB_200_late_sub_v1, KB_200_late, by = c("Site", "Subtype", 'Family')) 

# if subtype is just family (so doesn't have a specific abundance assinged from previous step) then compound all the family abundance then adding it 
# seperate NAs from already assinged subtype abundance 
pollen_JAM_200_early_sub_NA <- pollen_JAM_200_early_sub %>% filter(is.na(Abundance_for200))
pollen_JAM_200_early_sub_noNA <- pollen_JAM_200_early_sub %>% filter(!is.na(Abundance_for200))
# check which families are in the bee samples so I will compound those floral counts
# Amaryllidaceae, Asteraceae, Brassicaceae, Caryophyllaceae, Gramineae, Iridaceae, Myrtaceae, Rosaceae

pollen_JAM_200_late_sub_NA <- pollen_JAM_200_late_sub %>% filter(is.na(Abundance_for200))
pollen_JAM_200_late_sub_noNA <- pollen_JAM_200_late_sub %>% filter(!is.na(Abundance_for200))
# Asteraceae, Brassicaceae

pollen_KB_200_early_sub_NA <- pollen_KB_200_early_sub %>% filter(is.na(Abundance_for200))
pollen_KB_200_early_sub_noNA <- pollen_KB_200_early_sub %>% filter(!is.na(Abundance_for200))
# Ericaceae (Rhododendron)

pollen_KB_200_late_sub_NA <- pollen_KB_200_late_sub %>% filter(is.na(Abundance_for200))
# only unknown

## Compilling floral survey data 

# when there are multiple occurances of different subtypes of the same family
# e.g., multiple occurances of roses being available and uncommon, which get compilled to abundant 

# look at survey data then reasign abundance if needed
# JAM 200 early
JAM_200_early_to_merge <- JAM_200_early %>% filter(Family == 'Amaryllidaceae' | Family == 'Asteraceae' | Family == 'Brassicaceae' | Family == 'Caryophyllaceae' | Family == 'Gramineae' | Family == 'Iridaceae' | Family == 'Myrtaceae' | Family == 'Rosaceae')
 # Amaryllidaceae - keep rare 
 # Asteraceae - keep extremely abundant 
 # Brassicaceae - keep extremely abundant
 # Caryophyllaceae - keep extremely abundant
 # Gramineae - grass, doesn't exist in survey but was extremely abundant
 # Iridaceae - keep uncommon
 # Myrtaceae - keep uncommon
 # Rosaceae - make abundant 
# organize by abundance, remove duplicates, add rosaceae and grass abundance
JAM_200_early_to_merge <- JAM_200_early_to_merge %>%
  group_by(Family) %>%
  slice_max(Abundance_for200, n = 1, with_ties = FALSE) %>%
  ungroup()
# for abundance 
JAM_200_early_to_merge <- JAM_200_early_to_merge %>%
  mutate(Abundance_for200 = ifelse(
    Family == "Rosaceae",
    sub(3, 4, Abundance_for200),
    Abundance_for200
  ))
# add grass
JAM_200_early_to_merge <- JAM_200_early_to_merge %>% add_row(Site = 'JAM', Subsite = 'JAM', Range = '50m', Season = 'early/mid', Date = 'Nov 27 2024', Common_name = 'grass', Subtype = 'Gramineae', Family = 'Gramineae', Abundance_for200 = '5')

# JAM 200 late
JAM_200_late_to_merge <- JAM_200_late %>% filter(Family == 'Asteraceae' | Family == 'Brassicaceae')
 # Asteraceae - keep extremely abundant 
 # Brassicaceae - change to abundant
JAM_200_late_to_merge <- JAM_200_late_to_merge %>%
  group_by(Family) %>%
  slice_max(Abundance_for200, n = 1, with_ties = FALSE) %>%
  ungroup()
# for number abundance 
JAM_200_late_to_merge <- JAM_200_late_to_merge %>%
  mutate(Abundance_for200 = ifelse(
    Family == "Brassicaceae",
    sub(2, 4, Abundance_for200),
    Abundance_for200
  ))

# KB 200 early
KB_200_early %>% filter(Family == 'Ericaceae')
# doesn't exist in this survey
# add as zero

# KB 200 late
# only unknown type
pollen_KB_200_late_fam <- pollen_KB_200_late_sub_NA 


# remove common name and subsite, not accurate for compilled family taxa
JAM_200_early_to_merge <- JAM_200_early_to_merge %>% select(-Common_name, -Subsite, -Subtype, -Range, -Date)
JAM_200_late_to_merge <- JAM_200_late_to_merge %>% select(-Common_name, -Subsite, -Subtype, -Range, -Date)
pollen_KB_200_late_fam <- pollen_KB_200_late_fam %>% select(-Common_name, -Subsite, -Range, -Date) # keep subtype
# do KB early in a min

# make abundance numeric and remove empty columns
JAM_200_early_to_merge$Abundance_for200 <- as.numeric(JAM_200_early_to_merge$Abundance_for200)
pollen_JAM_200_early_sub_NA <- pollen_JAM_200_early_sub_NA %>% select(-Subsite, -Range, -Season, -Date, -Common_name, -Abundance_for200)
JAM_200_late_to_merge$Abundance_for200 <- as.numeric(JAM_200_late_to_merge$Abundance_for200)
pollen_JAM_200_late_sub_NA <- pollen_JAM_200_late_sub_NA %>% select(-Subsite, -Range, -Season, -Date, -Common_name, -Abundance_for200)

# combine the family-level df with the floral survey data
# JAM 200
pollen_JAM_200_early_fam <- left_join(pollen_JAM_200_early_sub_NA, JAM_200_early_to_merge, by = c('Family', 'Site')) 
pollen_JAM_200_late_fam <- left_join(pollen_JAM_200_late_sub_NA, JAM_200_late_to_merge, by = c('Family', 'Site')) 
# KB 200
 # early has one family, the rest unknown
 # late has one unknown 

# if there are NAs, it means the pollen sample is unknown or not in the survey

# not in survey gets 0
pollen_KB_200_early_fam <- pollen_KB_200_early_sub_NA %>%
  mutate(Abundance_for200 = ifelse(Family == "Ericaceae", 0, Abundance_for200))
# remove unneccessary columns 
pollen_KB_200_early_fam <- pollen_KB_200_early_fam %>% select(-Common_name, -Range, -Subsite, -Date)

# bind together all family and subtype data seperately 
pollen_200_fam <- rbind(pollen_JAM_200_early_fam, pollen_JAM_200_late_fam, pollen_KB_200_early_fam, pollen_KB_200_late_fam)
pollen_200_sub <- rbind(pollen_JAM_200_early_sub_noNA, pollen_JAM_200_late_sub_noNA, pollen_KB_200_early_sub_noNA)

# remove the same columns for sub as we did for family 
pollen_200_sub <- pollen_200_sub %>% select(-Subsite, -Date, -Range, -Common_name)

# bind all together
pollen_200_abundance <- rbind(pollen_200_sub, pollen_200_fam)

# check length of df
length(unique(pollen_200_abundance$Slide_code)) # 83 samples
length(pollen_200_abundance$Slide_code) # 147 rows


### 50 m survey ###

# use divided pollen samples from 200m for subtype-level observations
# then left_join with floral survey data
pollen_JAM_50_early_sub <- left_join(pollen_JAM_200_early_sub_v1, JAM_50_early, by = c("Site", "Subtype", 'Family')) 
pollen_JAM_50_late_sub <- left_join(pollen_JAM_200_late_sub_v1, JAM_50_late, by = c("Site", "Subtype", 'Family')) 
pollen_KB_50_early_sub <- left_join(pollen_KB_200_early_sub_v1, KB_50_early, by = c("Site", "Subtype", 'Family')) 
pollen_KB_50_late_sub <- left_join(pollen_KB_200_late_sub_v1, KB_50_late, by = c("Site", "Subtype", 'Family')) 

# if subtype is just family (so doesn't have a specific abundance assinged from the previous step) then compound all the family abundance then adding it 
# seperate NAs from already assinged subtype abundance 
pollen_JAM_50_early_sub_NA <- pollen_JAM_50_early_sub %>% filter(is.na(Abundance_for50))
pollen_JAM_50_early_sub_noNA <- pollen_JAM_50_early_sub %>% filter(!is.na(Abundance_for50))
# check which families are in the bee samples so I will compound those floral counts
# Amaryllidaceae, Asteraceae, Brassicaceae, Caryophyllaceae, Gramineae, Iridaceae, Myrtaceae, Rosaceae, Pyracantha (subtype)

pollen_JAM_50_late_sub_NA <- pollen_JAM_50_late_sub %>% filter(is.na(Abundance_for50))
pollen_JAM_50_late_sub_noNA <- pollen_JAM_50_late_sub %>% filter(!is.na(Abundance_for50))
# Asteraceae, Brassicaceae 

pollen_KB_50_early_sub_NA <- pollen_KB_50_early_sub %>% filter(is.na(Abundance_for50))
pollen_KB_50_early_sub_noNA <- pollen_KB_50_early_sub %>% filter(!is.na(Abundance_for50))
# Ericaceae (Rhododendron)

pollen_KB_50_late_sub_NA <- pollen_KB_50_late_sub %>% filter(is.na(Abundance_for50))
# only unknown
 
# look at survey data then reasign abundance if needed to compile family types
# JAM 50 early
JAM_50_early_to_merge <- JAM_50_early %>% filter(Family == 'Amaryllidaceae' | Family == 'Asteraceae' | Family == 'Brassicaceae' | Family == 'Caryophyllaceae' | Family == 'Gramineae' | Family == 'Iridaceae' | Family == 'Myrtaceae' | Family == 'Rosaceae' | Subtype == 'Pyracantha')
 # Amaryllidaceae - absent (only 200m range)
 # Asteraceae - keep extremely abundant 
 # Brassicaceae - keep extremely abundant
 # Caryophyllaceae - keep abundant
 # Gramineae - grass, doesn't exist in survey but was extremely abundant
 # Iridaceae - absent (only 200m range)
 # Myrtaceae - keep uncommon
 # Rosaceae - make available 
 # Pyracantha - absent (only 200m range)
# organize by abundance, remove duplicates, add rosaceae and grass abundance
JAM_50_early_to_merge <- JAM_50_early_to_merge %>%
  group_by(Family) %>%
  slice_max(Abundance_for50, n = 1, with_ties = FALSE) %>%
  ungroup()
# for abundance changes
JAM_50_early_to_merge <- JAM_50_early_to_merge %>%
  mutate(Abundance_for50 = ifelse(
    Family == "Rosaceae",
    sub(2, 3, Abundance_for50),
    Abundance_for50
  ))
# add types absent within 50m
JAM_50_early_to_merge$Abundance_for50 <- as.numeric(JAM_50_early_to_merge$Abundance_for50)
 # Amaryllidaceae
JAM_50_early_to_merge <- JAM_50_early_to_merge %>% add_row(Site = 'JAM', Subsite = 'JAM', Range = '50m', Season = 'early/mid', Date = 'Nov 27 2024', Common_name = NA, Subtype = 'Amaryllidaceae', Family = 'Amaryllidaceae', Abundance_for50 = 0)
 # Iridaceae
JAM_50_early_to_merge <- JAM_50_early_to_merge %>% add_row(Site = 'JAM', Subsite = 'JAM', Range = '50m', Season = 'early/mid', Date = 'Nov 27 2024', Common_name = NA, Subtype = 'Iridaceae', Family = 'Iridaceae', Abundance_for50 = 0)
 # Pyracantha
JAM_50_early_to_merge <- JAM_50_early_to_merge %>% add_row(Site = 'JAM', Subsite = 'JAM', Range = '50m', Season = 'early/mid', Date = 'Nov 27 2024', Common_name = NA, Subtype = 'Pyracantha', Family = 'Rosaceae', Abundance_for50 = 0)
# add grass
JAM_50_early_to_merge <- JAM_50_early_to_merge %>% add_row(Site = 'JAM', Subsite = 'JAM', Range = '50m', Season = 'early/mid', Date = 'Nov 27 2024', Common_name = 'grass', Subtype = 'Gramineae', Family = 'Gramineae', Abundance_for50 = 5)

# JAM 50 late
JAM_50_late_to_merge <- JAM_50_late %>% filter(Family == 'Asteraceae' | Family == 'Brassicaceae')
 # Asteraceae - change to extremely abundant 
 # Brassicaceae - keep rare
# keep highest dupe
JAM_50_late_to_merge <- JAM_50_late_to_merge %>%
  group_by(Family) %>%
  slice_max(Abundance_for50, n = 1, with_ties = FALSE) %>%
  ungroup()
# for number abundance 
JAM_50_late_to_merge <- JAM_50_late_to_merge %>%
  mutate(Abundance_for50 = ifelse(
    Family == "Asteraceae",
    sub(4, 5, Abundance_for50),
    Abundance_for50
  ))

# KB 50 early
KB_50_early %>% filter(Family == 'Ericaceae')
# doesn't exist in this survey
# add as zero

# KB 50 late
# only unknown type
pollen_KB_50_late_fam <- pollen_KB_50_late_sub_NA 


# remove common name and subsite, not accurate for compilled family taxa
JAM_50_early_to_merge <- JAM_50_early_to_merge %>% select(-Common_name, -Subsite, -Subtype, -Range, -Date)
JAM_50_late_to_merge <- JAM_50_late_to_merge %>% select(-Common_name, -Subsite, -Subtype, -Range, -Date)
pollen_KB_50_late_fam <- pollen_KB_50_late_fam %>% select(-Common_name, -Subsite, -Range, -Date) # keep subtype
# do KB early in a min

# make abundance numeric and remove empty columns
JAM_50_early_to_merge$Abundance_for50 <- as.numeric(JAM_50_early_to_merge$Abundance_for50)
pollen_JAM_50_early_sub_NA <- pollen_JAM_50_early_sub_NA %>% select(-Subsite, -Range, -Season, -Date, -Common_name, -Abundance_for50)
JAM_50_late_to_merge$Abundance_for50 <- as.numeric(JAM_50_late_to_merge$Abundance_for50)
pollen_JAM_50_late_sub_NA <- pollen_JAM_50_late_sub_NA %>% select(-Subsite, -Range, -Season, -Date, -Common_name, -Abundance_for50)


# combine the family-level df with the floral survey data
# JAM 50
pollen_JAM_50_early_fam <- left_join(pollen_JAM_50_early_sub_NA, JAM_50_early_to_merge, by = c('Family', 'Site')) 
pollen_JAM_50_late_fam <- left_join(pollen_JAM_50_late_sub_NA, JAM_50_late_to_merge, by = c('Family', 'Site')) 
# KB 50
 # early has one family, the rest unknown
 # late has one unknown 

# if there are NAs, it means the pollen sample is unknown or not in the survey

# not in survey gets 0
pollen_KB_50_early_fam <- pollen_KB_50_early_sub_NA %>%
  mutate(Abundance_for50 = ifelse(Family == "Ericaceae", 0, Abundance_for50))
# remove unneccessary columns 
pollen_KB_50_early_fam <- pollen_KB_50_early_fam %>% select(-Common_name, -Range, -Subsite, -Date)

# bind together all family and subtype data seperately 
pollen_50_fam <- rbind(pollen_JAM_50_early_fam, pollen_JAM_50_late_fam, pollen_KB_50_early_fam, pollen_KB_50_late_fam)
pollen_50_sub <- rbind(pollen_JAM_50_early_sub_noNA, pollen_JAM_50_late_sub_noNA, pollen_KB_50_early_sub_noNA)

# remove the same columns for sub as we did for family 
pollen_50_sub <- pollen_50_sub %>% select(-Subsite, -Date, -Range, -Common_name)

# bind all together
pollen_50_abundance <- rbind(pollen_50_sub, pollen_50_fam)

# check length of df
length(unique(pollen_50_abundance$Slide_code)) # 83 samples
length(pollen_50_abundance$Slide_code) # 159 rows, should be 148
# there are two duplicates because of the Rosaceae and Pyracantha changes. Easiest and cleanest way is to manually remove these 
# duplicates: JAM_OOO J-154 Rosaceae and JAM_OBO-P J-187 Pyracantha
# had to remove one at a time for some reason for it to work
pollen_50_abundance <- pollen_50_abundance %>% filter(Slide_code != 'J-187' | Abundance_for50 != 3 )
pollen_50_abundance <- pollen_50_abundance %>% filter(Slide_code != 'J-154' | Abundance_for50 != 0)

length(unique(pollen_50_abundance$Slide_code)) # 83 samples
length(pollen_50_abundance$Slide_code) # 148 rows, Pyracantha is absent and other Rosaceae is available, perfect!


## Bind 50m and 200m into one df for pollen samples

pollen_samples <- left_join(pollen_50_abundance, pollen_200_abundance)

# sample K-273 had rhododendron that was not found within the 200 meter radius, so the season came out as NA
# say season is early/mid 
pollen_samples <- pollen_samples %>% mutate(Season = ifelse(Slide_code == 'K-273', 'early/mid', Season))



```

```{r Behaviour_data}

# beehav has all individuals per nest
# beehav_full has repeated lines within a nest, unique date-nest combo
# beehav_sum has one line per nest with the highest number of females
# Social_status_con: most conservation
# Social_status_lib: includes two changes for nests J51, J75 and J56 to be social, because two bees painted the same day

beehav <- read_csv('Data/Behaviour/Video_logs_summary.csv')

# creat date column
beehav$Date_beehav <- with(beehav, paste(Year, paste0(Month, sep = '-', Day), sep = '-'))
beehav$Date_beehav <- as.Date(beehav$Date_beehav)
beehav <- beehav %>% select(-Day, -Month, -Year)

# Num_females_same_day: this column has the conservative estimate for the number of females partaking in nest care (pollen collection, vigilance with known ID, and digging) WITHIN ONE DAY
# vigilance with no ID is not counted because emerging females often rest at nest entrance without doing any other nest care

# are we missing social behaviour? doing this in R code so that my steps for more nuanced social diagnoses are reproducable 

## Compare with Paint IDs

IDs_JAM <- read_csv('Data/Paint_ID/Paint_IDs_JAM.csv')
IDs_KB <- read_csv('Data/Paint_ID/Paint_IDs_KB.csv')

# which nests have more than one female painted in them?
IDs_JAM %>%
  group_by(Nest) %>% 
  filter(n() > 1)  
IDs_KB %>%
  group_by(Nest) %>% 
  filter(n() > 1) 

# compare nests with more than one female painted with beehav data

beehav_potentially_social <- beehav %>% filter(Nest == 'J11' | Nest == 'J18' | Nest == 'J26' | Nest == 'J51' | Nest == 'J56' | Nest == 'J75' | Nest == 'J87' | Nest == 'J91' | Nest == 'J92' | Nest == 'K23')

# Date	  Bee_ID	Nest Notes
# 29-Oct	WYG	    11	 nest not filmed until Dec, only 1 unknown vigilance on Dec 10. 
# 12-Nov	PWB	    11	    -> keep solitary, no solid evidence of sociality
# 18-Nov	W-WWG	  18	 never filmed after being marked, and was weeks after previous 2 bees
# 25-Nov	G-OGP	  18	 OGP and WWG last seen Nov 25, No ID collects pollen Jan 16
# 16-Jan	P-PPG	  18	    -> P-PPG could have continued nest or reused nest, but wouldn't be for the first batch of brood
# 06-Nov	OBO-P	  26	 No ID (POB) filmed after OBO-P 6 weeks later then another NO ID 2 weeks later
# 06-Jan	P-POB	  26	    -> P-POB could have continued nest or reused nest, but wouldn't be for the first batch of brood
# 06-Jan	O-WOW	  51	 only Y-PPY filmed
# 06-Jan	Y-PPY	  51	    -> could be social 
# 07-Nov	PGP	    56	 no behaviour for J56 ever filmed
# 07-Nov	BWW	    56	    -> could be social
# 18-Nov	GWG	    75	 both collected pollen, but not on same day. GWG painted in Nov them collected pollen Dec 5. BBP painted and collcted pollen Dec 2
# 02-Dec	BBO	    75	    -> likely social
# 02-Dec	WPP	    87	 WPP behaviour never filmed
# 02-Dec	PBG	    87	    -> behaviour for only 2 workers ever filmed, keep as is
# 06-Jan	Y-YPP	  87	
# 06-Jan	W-PWO	  91	 a third bee (no ID) collected pollen on Jan 22 and these two stayed active till Feb
# 16-Jan	P-OOP-O	91	    -> no change, already had 3 bees active
# 16-Jan	O-OBB	  92	 three bees collected pollen on Jan 28th
# 16-Jan	Y-WYW	  92	    -> no change, already had 3 bees active
# 28-Jan	B-BPP	  92	
# 03-Dec	BBB-W	  23	activity a month apart
# 17-Jan	O-OOG	  23	    -> keep solitary, no solid evidence of sociality


## Summary:
 # J75 was social in early Dec, two diff bees 3 days apart. change to potentially social 
 # J51 and J56 each had two bees painted on same day but behaviour not recorded 
 # J11 could have been social because bees were painted within 2 weeks. But not close enough in time, so keep solitary
 # J26, J18, J87 and K23 keep as is, because the additional worker was painted at least 1.5 months later
 # J92 and J91 keep as is, already had 3 bees


## Only change J51, J56 and J75 to potentially social (after next step)


## Nest-level data unique date-nest combo

# make summary with only 1 row per nest with the highest number of females per date
beehav_full <- beehav %>%
  group_by(Nest, Date_beehav) %>%
  slice_max(Num_females_same_day, n = 1, with_ties = FALSE) %>%
  ungroup()

# keep only columns that make sense for summary df
beehav_full <- beehav_full %>% 
  select(Nest, Site, Num_females_same_day, Date_beehav, Nest_sociality_summary)


# mark nests as solitary or social for each date (may end up with nests that go back and forth between solitary and social)
beehav_full <- beehav_full %>% 
  mutate(Social_status_con = ifelse(Num_females_same_day > 1, "social", "solitary"))


## Change J51, J75 and J56 to potentially social

# J51 two bees painted on Jan 6
# J56 two bees painted Nov 7
# J75 bees filmed on Dec 2 and 5
beehav_full <- beehav_full %>% mutate(Social_status_lib = ifelse(Nest == 'J51' & Date_beehav == '2025-01-06' | Nest == 'J75' , 'social', Social_status_con))
# now add in line for J56
beehav_full <- beehav_full %>% add_row(Nest = 'J56', Site = 'JAM', Num_females_same_day = 0, Date_beehav = NA, Nest_sociality_summary = 'behaviour never recorded, adding social status based on paint markings', Social_status_con = 'solitary', Social_status_lib = 'social')


## Create one line per nest 
# with the maximum Num_females_same_day

beehav_sum <- beehav_full %>%
  group_by(Nest) %>%
  arrange(desc(Num_females_same_day)) %>%
  slice_head(n = 1) %>%
  ungroup()

# make sure changes are still there
# lib should be social, con should be solitary
beehav_sum %>% filter(Nest == 'J75' | Nest == 'J51' | Nest == 'J56')


## Counting not including 0 females
beehav_sum %>% 
  filter(Num_females_same_day >= 1) %>% 
  group_by(Site) %>% 
  count(Social_status_con)
# JAM social    5
# JAM solitary  24 
# KB solitary   12

## Counting not including 0 females #
beehav_sum %>% 
  filter(Num_females_same_day >= 1) %>% 
  group_by(Site) %>% 
  count(Social_status_lib)
# JAM social    7 + 1 (J56) = 8 # doesn't include J56 which never had observations, so add manually 
# JAM solitary  22 
# KB solitary   12


length(unique(beehav_sum$Nest)) # 51 nests observed 
table(beehav_sum$Social_status) # 5 social, 46 solitary

# # how many marked bees did we observe?
# # first remove unknowns
# beehav_IDs <- beehav %>% filter(!grepl('Male', Bee_ID))
# beehav_IDs <- beehav_IDs %>% filter(!grepl('No ID', Bee_ID))
# beehav_IDs <- beehav_IDs %>% filter(!grepl('Unknown', Bee_ID))
# length(unique(beehav_IDs$Bee_ID))
# # 39

```

```{r Pollen_and_Sociality}

## Combine dataframes

# Behaviour data
# first, inspect IDs of 
list(unique(beehav$Bee_ID))
# filter out No IDs cause I only have pollen from known bees
beehav_known <- beehav %>%
  filter(!str_detect(Bee_ID, "No ID"),
         Bee_ID != "Unknown",
         Bee_ID != "Males",
         Bee_ID != "Male")
# order and inspect
beehav_known <- beehav_known[order(beehav_known$Bee_ID),]
# combine ID with site in case the same ID was used for both sites
beehav_known$Bee_ID <- as.character(beehav_known$Bee_ID)
beehav_known$Bee_ID <- paste(beehav_known$Site, beehav_known$Bee_ID, sep = '_') 
table(beehav_known$Bee_ID) 

# Pollen data
list(unique(pollen$Bee_ID))

# before merging dfs, compare the IDs between them
# pollen list
pollen_IDs_list <- as.data.frame(pollen$Bee_ID)
colnames(pollen_IDs_list) <- "bee_ID"
pollen_IDs_list <- distinct(pollen_IDs_list)
# behaviour list
beehav_IDs_list <- as.data.frame(beehav_known$Bee_ID)
colnames(beehav_IDs_list) <- "bee_ID"
beehav_IDs_list <- distinct(beehav_IDs_list)
# compare
ID_comparison <- data.frame(
  Bee_ID = union(beehav_IDs_list$bee_ID, pollen_IDs_list$bee_ID),
  Beehav_data = union(beehav_IDs_list$bee_ID, pollen_IDs_list$bee_ID) %in% beehav_IDs_list$bee_ID,
  Pollen_sample = union(beehav_IDs_list$bee_ID, pollen_IDs_list$bee_ID) %in% pollen_IDs_list$bee_ID)

# show bees with both data
bees_both_data <- ID_comparison %>% filter(Beehav_data == TRUE & Pollen_sample == TRUE)


## Double check Bee ID codes

# check if the core code (three thorax colours) are the same
ID_comparison <- ID_comparison %>%
  mutate(
    code = str_extract(Bee_ID, "(?<=[_-])[A-Z]{3}"))  # 3 caps after "_" or "-"

# manually scan to see that all duplciates are from different sites
ID_comparison %>%
  filter(!is.na(code)) %>%
  group_by(code) %>%
  filter(n() > 1) %>%
  arrange(code) # looking good


## Match pollen and behaviour data

# if the bee ID is in the bees_both_data, then extract all their rows from pollen data, and all of the nest IDs from beehav

pollen_beehav <- pollen %>%
  filter(Bee_ID %in% bees_both_data$Bee_ID)

# assining bees the Nest IDs in the pollen data
nest_IDs_for_pollen_samples <- beehav_known %>% select(Nest, Bee_ID)
# remove duplicates
nest_IDs_for_pollen_samples <- distinct(nest_IDs_for_pollen_samples) 
# join
pollen_beehav <- left_join(pollen_beehav, nest_IDs_for_pollen_samples)
# move Nest column to first
pollen_beehav <- pollen_beehav %>%
  select(Nest, everything())


## Manually see which dates are closest for the nests that are social (tried and failed to code this)

# look at the nests that have been social for both pollen and behaviour
beehav_full %>% filter(Social_status_con == 'social')
beehav_full %>% filter(Social_status_lib == 'social')

social_nest_sum <- beehav_full %>% filter(Nest == 'J100' | Nest == 'J18' | Nest == 'J87' | Nest == 'J91' | Nest == 'J92' | Nest == 'J51' | Nest == 'J56' | Nest == 'J75')
social_pollen_sum <- pollen_beehav %>% filter(Nest == 'J100' | Nest == 'J18' | Nest == 'J87' | Nest == 'J91' | Nest == 'J92' | Nest == 'J51' | Nest == 'J56' | Nest == 'J75')

# made this table by comparing on these two dfs

# nest -- pollen slide: pollen sample date --- closest social status date - social status
 # J100 --  J-182: 2025-01-15 --- 2025-01-16 - solitary
 # J100 --  J-256: 2025-02-04 --- 2025-02-04 - social
 # J18 --   J-291: 2024-11-19 --- 2024-11-19 - social
 # J18 --   J-233: 2024-11-25 --- 2024-11-25 - social
 # J87 --   J-271: 2025-01-07 --- 2025-01-07 - social
 # J87 --   J-197: 2025-01-15 --- 2025-01-15 - solitary
 # J87 --   J-113: 2025-01-07 --- 2025-01-07 - social
 # J87 --   J-219: 2025-01-06 --- 2025-01-06 - solitary <-- only one day apart from social
 # J91 --   J-193: 2025-01-16 --- 2025-01-16 - social
 # J91 --   J-250: 2025-01-22 --- 2025-01-22 - social
 # J91 --   J-137: 2025-01-16 --- 2025-01-16 - social
 # J91 --   J-249: 2025-02-03 --- 2025-02-03 - solitary
 # J92 --   J-226: 2025-01-28 --- 2025-01-28 - social
 # J92 --   J-199: 2025-02-03 --- 2025-02-03 - social
 # J92 --   J-133: 2025-02-03 --- 2025-02-03 - social
 # J51 --   J-145: 2025-01-15 --- 2025-01-16 - solitary <-- this nest is only social when I 
 # J51 --   J-208: 2025-01-16 --- 2025-01-16 - solitary     painted two bees on same day
 # J75 --   J-150: 2024-12-05 --- 2024-12-02 - social <-- 2 bees collecting pollen 2 days apart
 # J56 -- no pollen samples 


# make column with social status
# all samples above get social if labelled social, otherwise solitary
# conservative (J75 is solitary)
pollen_beehav <- pollen_beehav %>% mutate(Social_status_at_time_con = ifelse(Slide_code == 'J-256' | Slide_code == 'J-291' | Slide_code == 'J-233' | Slide_code == 'J-271' | Slide_code == 'J-113' | Slide_code == 'J-193' | Slide_code == 'J-250' | Slide_code == 'J-137' | Slide_code == 'J-226' | Slide_code == 'J-199' | Slide_code == 'J-133', 'social', 'solitary'))
# liberal (J75 is social)
pollen_beehav <- pollen_beehav %>% mutate(Social_status_at_time_lib = ifelse(Slide_code == 'J-256' | Slide_code == 'J-291' | Slide_code == 'J-233' | Slide_code == 'J-271' | Slide_code == 'J-113' | Slide_code == 'J-193' | Slide_code == 'J-250' | Slide_code == 'J-137' | Slide_code == 'J-226' | Slide_code == 'J-199' | Slide_code == 'J-133' | Slide_code == 'J-150', 'social', 'solitary'))

# make a column to say if it ever becomes social, it stays social

## Now organized by date within each nest, only two nests revert to solitary 

# nest -- pollen slide: pollen sample date --- closest social status date - social status
 # J100 --	J-182:	2025-01-15 ---  2025-01-16 -	solitary
 # J100 --	J-256:	2025-02-04 ---  2025-02-04 -	social
 # J18 --	  J-291:	2024-11-19 ---	2024-11-19 -	social
 # J18 --	  J-233:	2024-11-25 ---	2024-11-25 -	social
 # J87 --	  J-219:	2025-01-06 ---	2025-01-06 -	solitary
 # J87 --  	J-271:	2025-01-07 ---	2025-01-07 -	social
 # J87 --  	J-113:	2025-01-07 ---	2025-01-07 -	social
 # J87 --  	J-197:	2025-01-15 ---	2025-01-15 -	solitary <-- change to social
 # J91 --	  J-193:	2025-01-16 ---	2025-01-16 -	social
 # J91 --	  J-137:	2025-01-16 ---	2025-01-16 -	social
 # J91 --	  J-250:	2025-01-22 ---	2025-01-22 -	social
 # J91 --	  J-249:	2025-02-03 ---	2025-02-03 -	solitary <-- change to social
 # J92 --	  J-226:	2025-01-28 ---	2025-01-28 -	social
 # J92 --	  J-199:	2025-02-03 ---	2025-02-03 -	social
 # J92 --	  J-133:	2025-02-03 ---	2025-02-03 -	social
 # J51 --   J-145:  2025-01-15 --- 2025-01-16 - social <-- change to social *
 # J51 --   J-208:  2025-01-16 --- 2025-01-16 - social <-- change to social 
 # J75 --   J-150:  2024-12-05 --- 2024-12-02 - social
 # J56 -- no pollen samples 

# * two bees painted the same day on Jan 6, so then keep this nest social for Social_status_ever

# conservative (J75 and J51 as solitary)
pollen_beehav <- pollen_beehav %>% mutate(Social_status_ever_con = ifelse(Slide_code == 'J-256' | Slide_code == 'J-291' | Slide_code == 'J-233' | Slide_code == 'J-271' | Slide_code == 'J-113' | Slide_code == 'J-193' | Slide_code == 'J-250' | Slide_code == 'J-137' | Slide_code == 'J-226' | Slide_code == 'J-199' | Slide_code == 'J-133' | Slide_code == 'J-197' | Slide_code == 'J-249', 'social', 'solitary'))
# liberal (J75 and J51 as solitary)
pollen_beehav <- pollen_beehav %>% mutate(Social_status_ever_lib = ifelse(Slide_code == 'J-256' | Slide_code == 'J-291' | Slide_code == 'J-233' | Slide_code == 'J-271' | Slide_code == 'J-113' | Slide_code == 'J-193' | Slide_code == 'J-250' | Slide_code == 'J-137' | Slide_code == 'J-226' | Slide_code == 'J-199' | Slide_code == 'J-133' | Slide_code == 'J-197' | Slide_code == 'J-249' | Slide_code == 'J-150' | Slide_code == 'J-145' | Slide_code == 'J-208', 'social', 'solitary'))


# how many pollen samples and nests do we have pollen and behaviour data for?
length(unique(pollen_beehav$Slide_code)) # 45
length(unique(pollen_beehav$Nest)) # 22





```

```{r Individual_ID}

## Create number for each bee instead of code
# Site-Nest-ID

paint_IDs_JAM <- read_csv('Data/Paint_ID/Paint_IDs_JAM.csv')
paint_IDs_KB <- read_csv('Data/Paint_ID/Paint_IDs_KB.csv')

# add site intitial, index, and paste 
paint_IDs_JAM <- paint_IDs_JAM %>% mutate(J = 'J')
paint_IDs_JAM <- tibble::rowid_to_column(paint_IDs_JAM, "ID")
paint_IDs_JAM$Num_ID <- paste(paint_IDs_JAM$J, paint_IDs_JAM$ID, sep = '-') 

# same for other site 
paint_IDs_KB <- paint_IDs_KB %>% mutate(K = 'K')
paint_IDs_KB <- tibble::rowid_to_column(paint_IDs_KB, "ID")
paint_IDs_KB$Num_ID <- paste(paint_IDs_KB$K, paint_IDs_KB$ID, sep = '-') 

# combine ID with site to match with earlier dfs
paint_IDs_JAM$Bee_ID <- as.character(paint_IDs_JAM$Bee_ID)
paint_IDs_JAM$Bee_ID <- paste('JAM', paint_IDs_JAM$Bee_ID, sep = '_') 
paint_IDs_KB$Bee_ID <- as.character(paint_IDs_KB$Bee_ID)
paint_IDs_KB$Bee_ID <- paste('KB', paint_IDs_KB$Bee_ID, sep = '_') 

# take columns I need
paint_IDs_JAM <- paint_IDs_JAM %>% select(Bee_ID, Num_ID)
paint_IDs_KB <- paint_IDs_KB %>% select(Bee_ID, Num_ID)

## some NAs from markings that don't match (different ways we wrote the code in the marking sheets vs video recordings)
# JAM_P-PBG = PBG
# JAM_PiBP = PiBPi
# JAM_PPG = P-PPG
# JAM_PrBP-W = PuBPu-W
# JAM_Y-YYY <- unsure which bee this would be, potentially forgot to write down the colour combo? keep as it's on ID
# KB_WWG = WGG <-- in my notes I say 'looks like WWG'

# replace the names for JAM
paint_IDs_JAM <- paint_IDs_JAM %>% 
  mutate(Bee_ID_v2 = ifelse(Bee_ID == 'JAM_PBG', 'JAM_P-PBG',
                            ifelse(Bee_ID == 'JAM_PiBPi', 'JAM_PiBP', 
                                   ifelse(Bee_ID == 'JAM_P-PPG', 'JAM_PPG', 
                                          ifelse(Bee_ID == 'JAM_PuBPu-W', 'JAM_PrBP-W', Bee_ID )))))

# replace the names for KB
paint_IDs_KB <- paint_IDs_KB %>% 
  mutate(Bee_ID_v2 = ifelse(Bee_ID == 'KB_WGG', 'KB_WWG', Bee_ID))

# change the  column names
paint_IDs_JAM <- paint_IDs_JAM %>% select(-Bee_ID)
paint_IDs_KB <- paint_IDs_KB %>% select(-Bee_ID)

paint_IDs_JAM <- paint_IDs_JAM %>% rename(Bee_ID = Bee_ID_v2)
paint_IDs_KB <- paint_IDs_KB %>% rename(Bee_ID = Bee_ID_v2)

# bind together
paint_IDs <- rbind(paint_IDs_JAM, paint_IDs_KB)

# bind to dataframes
pollen_samples <- left_join(pollen_samples, paint_IDs, by = 'Bee_ID')

# mark Y-YYY as J-85
pollen_samples <- pollen_samples %>% mutate(Num_ID = ifelse(Bee_ID == 'JAM_Y-YYY', 'J-85', Num_ID))


```

```{r Abundance_for_RDA}


## Make df for abundance with all plant families for the RDA

# pivot the abundance wider
compiled_JAM_50_early_wide <- pivot_wider(compiled_JAM_50_early, names_from = 'Family', values_from = 'Abundance_for50_comp', id_cols = c(Site, Season))
compiled_JAM_50_late_wide <- pivot_wider(compiled_JAM_50_late, names_from = 'Family', values_from = 'Abundance_for50_comp', id_cols = c(Site, Season))
compiled_KB_50_early_wide <- pivot_wider(compiled_KB_50_early, names_from = 'Family', values_from = 'Abundance_for50_comp', id_cols = c(Site, Season))
compiled_KB_50_late_wide <- pivot_wider(compiled_KB_50_late, names_from = 'Family', values_from = 'Abundance_for50_comp', id_cols = c(Site, Season))
compiled_JAM_200_early_wide <- pivot_wider(compiled_JAM_200_early, names_from = 'Family', values_from = 'Abundance_for200_comp', id_cols = c(Site, Season))
compiled_JAM_200_late_wide <- pivot_wider(compiled_JAM_200_late, names_from = 'Family', values_from = 'Abundance_for200_comp', id_cols = c(Site, Season))
compiled_KB_200_early_wide <- pivot_wider(compiled_KB_200_early, names_from = 'Family', values_from = 'Abundance_for200_comp', id_cols = c(Site, Season))
compiled_KB_200_late_wide <- pivot_wider(compiled_KB_200_late, names_from = 'Family', values_from = 'Abundance_for200_comp', id_cols = c(Site, Season))

# arrange by date
pollen_samples <- pollen_samples %>% arrange(Date_pollen)

# take columns I need
pollen_samples_for_rda <- pollen_samples %>% select(Site, Season, Num_ID, Slide_code, Family, Count_scaled)

# remove unknowns
pollen_samples_for_rda_known <- pollen_samples_for_rda %>% filter(!is.na(Season))

# pivot wider so the rows are identical
pollen_samples_for_rda_known <- pivot_wider(pollen_samples_for_rda_known, names_from = 'Family', values_from = 'Count_scaled', id_cols = c(Num_ID, Slide_code, Site, Season))

# delete columns of pollen counts
pollen_samples_for_rda_known <- pollen_samples_for_rda_known %>% select(Num_ID, Slide_code, Site, Season)


# divide by survey, most confident way to ensure proper combination 
pollen_rda_JAM_early <- pollen_samples_for_rda_known %>% filter(Season == 'early/mid' & Site == 'JAM')
pollen_rda_JAM_late <- pollen_samples_for_rda_known %>% filter(Season == 'late' & Site == 'JAM')
pollen_rda_KB_early <- pollen_samples_for_rda_known %>% filter(Season == 'early/mid' & Site == 'KB')
# pollen_rda_KB_late <- pollen_samples_for_rda_known %>% filter(Season == 'late' & Site == 'KB') <-- 0 observations


## 50 m

rda_abundance_JAM_50_early <- left_join(pollen_rda_JAM_early, compiled_JAM_50_early_wide)
rda_abundance_JAM_50_late <- left_join(pollen_rda_JAM_late, compiled_JAM_50_late_wide)
rda_abundance_KB_50_early <- left_join(pollen_rda_KB_early, compiled_KB_50_early_wide)

# before joining JAM dfs, they all need the same column names
setdiff(names(rda_abundance_JAM_50_early), names(rda_abundance_JAM_50_late))
# in early but not late df: "Argophyllaceae" "Asphodelaceae"  "Celastraceae"   "Geraniaceae"   
setdiff(names(rda_abundance_JAM_50_late), names(rda_abundance_JAM_50_early))
# in late but not early: "Cucurbitaceae" "Iridaceae"     "Lamiaceae"     "Liliaceae"     "Polygonaceae"  "Rutaceae"      "Tropaeolaceae"

# make the new columns and fill with 0
new_cols_for_early_50 <- c("Cucurbitaceae", "Iridaceae", "Lamiaceae", "Liliaceae", "Polygonaceae", "Rutaceae", "Tropaeolaceae")
rda_abundance_JAM_50_early[new_cols_for_early_50] <- 0
new_cols_for_late_50 <- c("Argophyllaceae", "Asphodelaceae", "Celastraceae", "Geraniaceae")
rda_abundance_JAM_50_late[new_cols_for_late_50] <- 0

# bind these JAM 50 surveys together
rda_abundance_JAM_50 <- rbind(rda_abundance_JAM_50_late, rda_abundance_JAM_50_early)

# compare JAM to KB
setdiff(names(rda_abundance_JAM_50), names(rda_abundance_KB_50_early))
# "Caprifoliaceae" "Cucurbitaceae"  "Iridaceae"      "Lamiaceae"      "Liliaceae"      "Rutaceae"       "Argophyllaceae" "Asphodelaceae"  "Celastraceae"   "Geraniaceae" 
setdiff(names(rda_abundance_KB_50_early), names(rda_abundance_JAM_50))
# "Asparagaceae"  "Boraginaceae"  "Linaceae"      "Orobanchaceae" "Papaveraceae"  "Violaceae"    

# make the new columns 
new_cols_for_KB_50 <- c("Caprifoliaceae", "Cucurbitaceae", "Iridaceae", "Lamiaceae", "Liliaceae", "Rutaceae", "Argophyllaceae", "Asphodelaceae", "Celastraceae", "Geraniaceae")
rda_abundance_KB_50_early[new_cols_for_KB_50] <- 0
new_cols_for_JAM_50 <- c("Asparagaceae", "Boraginaceae", "Linaceae", "Orobanchaceae", "Papaveraceae", "Violaceae")
rda_abundance_JAM_50[new_cols_for_JAM_50] <- 0

# bind JAM and KB together
rda_abundance_50 <- rbind(rda_abundance_JAM_50, rda_abundance_KB_50_early)


## 200 m

rda_abundance_JAM_200_early <- left_join(pollen_rda_JAM_early, compiled_JAM_200_early_wide)
rda_abundance_JAM_200_late <- left_join(pollen_rda_JAM_late, compiled_JAM_200_late_wide)
rda_abundance_KB_200_early <- left_join(pollen_rda_KB_early, compiled_KB_200_early_wide)

# before joining JAM dfs, they all need the same column names
setdiff(names(rda_abundance_JAM_200_early), names(rda_abundance_JAM_200_late))
# in early but not late df: "Anacardiaceae"  "Argophyllaceae" "Asteliaceae"    "Celastraceae"   "Cistaceae"      "Limnanthaceae"  "Malvaceae"  "Paeoniaceae"    "Rhamnaceae"     "Rubiaceae"      "Theaceae"   
setdiff(names(rda_abundance_JAM_200_late), names(rda_abundance_JAM_200_early))
# in late but not early: "Aizoaceae"        "Apocynaceae"      "Campanulaceae"    "Cucurbitaceae"    "Magnoliaceae"     "Scrophulariaceae"

# make the new columns and fill with 0
new_cols_for_early_200 <- c("Aizoaceae", "Apocynaceae", "Campanulaceae", "Cucurbitaceae", "Magnoliaceae", "Scrophulariaceae")
rda_abundance_JAM_200_early[new_cols_for_early_200] <- 0
new_cols_for_late_200 <- c("Anacardiaceae", "Argophyllaceae", "Asteliaceae", "Celastraceae", "Cistaceae", "Limnanthaceae", "Malvaceae", "Paeoniaceae", "Rhamnaceae", "Rubiaceae", "Theaceae")
rda_abundance_JAM_200_late[new_cols_for_late_200] <- 0

# bind these JAM 50 surveys together
rda_abundance_JAM_200 <- rbind(rda_abundance_JAM_200_late, rda_abundance_JAM_200_early)

# compare JAM to KB
setdiff(names(rda_abundance_JAM_200), names(rda_abundance_KB_200_early))
# "Alstroemeriaceae" "Amaryllidaceae"   "Araceae"          "Campanulaceae"    "Caprifoliaceae"   "Commelinaceae"   "Crassulaceae"     "Cucurbitaceae"    "Ericaceae"        "Escalloniaceae"   "Euphorbiaceae"    "Geraniaceae"     "Hydrangeaceae"    "Iridaceae"        "Liliaceae"        "Magnoliaceae"     "Montiaceae"       "Nymphaeaceae"    "Oleaceae"   "Plumbaginaceae"   "Saxifragaceae"    "Anacardiaceae"    "Argophyllaceae"   "Celastraceae"    "Cistaceae"        "Limnanthaceae"    "Malvaceae"        "Paeoniaceae"      "Rhamnaceae"       "Theaceae"
setdiff(names(rda_abundance_KB_200_early), names(rda_abundance_JAM_200))
# "Chenopodiaceae" "Elaeocarpaceae" "Gentianaceae"   "Griseliniaceae" "Icacinaceae"    "Linaceae"       "Loranthaceae"   "Moraceae"       "Pittosporaceae" "Rousseaceae"    "Smilacaceae"       

# make the new columns 
new_cols_for_KB_200 <- c("Alstroemeriaceae", "Amaryllidaceae", "Araceae", "Campanulaceae", "Caprifoliaceae", "Commelinaceae", "Crassulaceae", "Cucurbitaceae", "Ericaceae", "Escalloniaceae", "Euphorbiaceae", "Geraniaceae", "Hydrangeaceae", "Iridaceae", "Liliaceae", "Magnoliaceae", "Montiaceae", "Nymphaeaceae", "Oleaceae", "Plumbaginaceae", "Saxifragaceae", "Anacardiaceae", "Argophyllaceae", "Celastraceae", "Cistaceae", "Limnanthaceae", "Malvaceae", "Paeoniaceae", "Rhamnaceae", "Theaceae") 
rda_abundance_KB_200_early[new_cols_for_KB_200] <- 0
new_cols_for_JAM_200 <- c("Chenopodiaceae", "Elaeocarpaceae", "Gentianaceae", "Griseliniaceae", "Icacinaceae", "Linaceae", "Loranthaceae", "Moraceae", "Pittosporaceae", "Rousseaceae", "Smilacaceae")
rda_abundance_JAM_200[new_cols_for_JAM_200] <- 0

# bind JAM and KB together
rda_abundance_200 <- rbind(rda_abundance_JAM_200, rda_abundance_KB_200_early)


```

```{r Editing_data_for_results}


## Editing data for analyses and figures


## Create day of season 

season_start <- as.Date("2024-11-07") # first day of collected pollen
pollen_samples <- pollen_samples %>%
  mutate(Day_of_season = as.integer(Date_pollen - season_start) + 1)
# move earlier
pollen_samples <- pollen_samples %>% relocate(Day_of_season, .after = Date_pollen)



## Create richness (number of plant subtypes)
# doing this now once we have social/ nest-level data

# richness at the nest level for all samples compiled
pollen_beehav <- pollen_beehav %>%
  group_by(Nest) %>%
  mutate(Richness_nest = n_distinct(Subtype)) %>%
  ungroup()

# richness per sample
pollen_beehav <- pollen_beehav %>%
  group_by(Slide_code) %>%
  mutate(Richness_ind = n_distinct(Subtype)) %>%
  ungroup()

# average richness at the individual level for each sample
pollen_beehav <- pollen_beehav %>%
  group_by(Bee_ID, Slide_code) %>%
  mutate(Richness_ind_mean_v1 = n_distinct(Subtype)) %>%
  ungroup()
pollen_beehav <- pollen_beehav %>%
  group_by(Bee_ID) %>%
  mutate(Richness_ind_mean = mean(Richness_ind_mean_v1)) %>%
  ungroup()

# keep columns for individuals
pollen_beehav_ind <- pollen_beehav %>% select(Nest, Bee_ID, Site, Date_pollen, Richness_ind_mean, Richness_ind, Social_status_at_time_con, Social_status_at_time_lib)
# remove duplicates
pollen_beehav_ind <- distinct(pollen_beehav_ind)

# keep columns for nests
pollen_beehav_nest <- pollen_beehav %>% select(Nest, Site, Richness_nest, Social_status_at_time_con, Social_status_at_time_lib)
# remove duplicates
pollen_beehav_nest <- distinct(pollen_beehav_nest)
# manually for nests both social and solitary
pollen_beehav_nest <- pollen_beehav_nest %>%
  filter(!(Social_status_at_time_con == "solitary" &
           Nest %in% c("J100", "J87", "J91")))



## For diversity and cumulative diversity 

# # pivot wider
# pollen_samples_wide <- pollen_samples %>% select(Bee_ID, Slide_code, Date_pollen, Subtype, Count_scaled)
# pollen_samples_wide <- pivot_wider(pollen_samples_wide, names_from = 'Subtype', values_from = 'Count_scaled', id_cols = c(Bee_ID, Slide_code, Date_pollen))
# 
# # replace NA with 0
# pollen_samples_wide[is.na(pollen_samples_wide)] <- 0
# 
# # take just the samples and calculate diversity
# just_pollen <- pollen_samples_wide %>% select(-Slide_code, -Bee_ID, -Date_pollen)
# diversity <- just_pollen %>% diversity(index = "shannon")
# # the zeros are flower constant bees
# 
# # make df and rename with capital
# diversity <- as.data.frame(diversity)
# diversity <- diversity %>% rename(Diversity = diversity)
# 
# # add the descriptive info back in
# diversity$Slide_code <- pollen_samples_wide$Slide_code
# diversity$Bee_ID <- pollen_samples_wide$Bee_ID
# to_join <- pollen_samples %>% select(-...1, -Family, -Subtype, -Count, -Count_scaled, -Season, -Abundance_for50, -Abundance_for200)
# to_join <- distinct(to_join)
# pollen_diversity <- inner_join(to_join, diversity)
# 
# # create day of season, better than date for model
# season_start <- as.Date("2024-11-07") # first day of collected pollen
# pollen_diversity <- pollen_diversity %>%
#   mutate(Day_of_season = as.integer(Date_pollen - season_start) + 1)
# # move earlier
# pollen_diversity <- pollen_diversity %>% relocate(Day_of_season, .after = 5)
# 
# # Cumulative diversity
# 
# # take column names of taxa
# taxa_cols <- pollen_samples_wide %>%
#   select(Ranunculus:Unknown_7) %>%
#   names()
# 
# # make day of season
# pollen_samples_wide <- pollen_samples_wide %>%
#   mutate(Day_of_season = as.integer(Date_pollen - season_start) + 1)
# pollen_samples_wide <- pollen_samples_wide %>% relocate(Day_of_season, .after = 2)
# 
# 
# # pull the cumultive counts of pollen and types within each bee
# pollen_samples_cumu <- pollen_samples_wide %>%
#   arrange(Day_of_season) %>%   
#   group_by(Bee_ID) %>%
#   mutate(across(all_of(taxa_cols), cumsum)) %>%
#   ungroup() 
# 
# # make cumulative diversity 
# pollen_samples_cumu$Diversity_cumu <- diversity(pollen_samples_cumu[, taxa_cols], index = "shannon")


# remove first index columns


```

```{r Saving}

## Saving wrangled data

# pollen data
write.csv(pollen_samples, 'Data/Pollen_and_Surveys/Pollen_samples_data_cleaned.csv')

# nest-level data summary
write.csv(beehav_sum, 'Data/Behaviour/Behaviour_nest_summary_cleaned.csv')

# nest-level data all social statuses
write.csv(beehav_full, 'Data/Behaviour/Behaviour_nest_full_cleaned.csv')

# pollen samples and sociality 
write.csv(pollen_beehav, 'Data/Behaviour/Pollen_and_behaviour_cleaned.csv')

# pollen richness for individuals  
write.csv(pollen_beehav_ind, 'Data/Pollen_and_Surveys/Pollen_richness_individuals_cleaned.csv')

# pollen richness for nests  
write.csv(pollen_beehav_nest, 'Data/Pollen_and_Surveys/Pollen_richness_nests_cleaned.csv')

# survey data for RDA
write.csv(rda_abundance_50, 'Data/Pollen_and_Surveys/Abundance_50m_cleaned.csv')
write.csv(rda_abundance_200, 'Data/Pollen_and_Surveys/Abundance_200m_cleaned.csv')


```

```{r Phylogeny}

# library(phytools)

# trying to make a lasioglossum tree to see the closest relatives of l sordidum to look up their sociality

# load tree 
# 
# lasio_tree <- read.newick('/Users/faith/Desktop/U Ottawa/PhD Chapter 3/sweat_bee_ecology/Data/Behaviour/Lasioglossum_tree.nwk')
# 
# # BeeTree loads 1001 trees. The first tree is the maximum likelyhood tree, which we want, and 1000 bootstrapped samples
# # isolate the maximum likelyhood tree
# lasio_tree <- lasio_tree[[1]] 
# 
# # save it
# jpeg(file.path(getwd(), "tree.jpg"),
#      width = 2080, height = 8500, res = 500)
# plot.phylo(lasio_tree,
#            show.tip.label = TRUE,
#            edge.width = 1,
#            label.offset = 0.005,
#            cex = 0.25,
#            font = 1)
# dev.off()

```
