---
title: "02_Figures"
format: html
editor: visual
---

```{r Load}

library(tidyverse)
library(ggplot2)
theme_set(theme_classic())

# pollen data
pollen_samples <- read_csv('Data/Pollen_and_Surveys/Pollen_samples_data_cleaned.csv')

# nest-level data summary
beehav_sum <- read_csv('Data/Behaviour/Behaviour_nest_summary_cleaned.csv')

# nest-level data all social statuses
beehav_full <- read_csv('Data/Behaviour/Behaviour_nest_full_cleaned.csv')

# pollen_samples and behaviour data
pollen_beehav <- read_csv('Data/Behaviour/Pollen_and_behaviour_cleaned.csv')

# pollen richness for individuals  
pollen_beehav_ind <- read_csv('Data/Pollen_and_Surveys/Pollen_richness_individuals_cleaned.csv')

# pollen richness for nests  
pollen_beehav_nest <- read_csv('Data/Pollen_and_Surveys/Pollen_richness_nests_cleaned.csv')






```

```{r Pollen_figures}


# make date labels for the figure
pollen_samples <- pollen_samples %>%
  mutate(
    Date_label  = format(Date_pollen, "%b %d"),                    
    Date_label  = factor(Date_label, levels = format(sort(unique(Date_pollen)), "%b %d")))

# reorder the pollen_samples counts within each bee from smallest to largest pollen_samples count
pollen_samples <- pollen_samples %>%
  group_by(Bee_ID, Date_pollen) %>%
  arrange(Count)


# pollen_samples samples by individual
pollen_samples %>% 
  filter(Num_of_samples > 1) %>% 
  arrange(Date_pollen) %>%
  ggplot(aes(x = Date_label, y = Count, fill = Family)) +
  geom_col(position = "fill", width = 0.8) +
  labs(x = "Date", y = "Proportion of pollen") +
  facet_wrap(~ Bee_ID, scales = "free_x")  + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.6))  + 
  theme(
  strip.background = element_blank(),
  strip.text = element_text(size = 8))



# pollen_samples types bees collected, summary 
# first make df for the sample size for above figures
n_df_KB <- pollen_samples %>%
  filter(Site == 'KB') %>% 
  group_by(Date_label) %>%
  summarise(N_bees = length(unique(Slide_code))) 

n_df_JAM <- pollen_samples %>%
  filter(Site == 'JAM') %>% 
  group_by(Date_label) %>%
  summarise(N_bees = length(unique(Slide_code))) 

pollen_samples %>% 
  filter(Site == 'KB') %>% 
  ggplot(aes(x = Date_label, y = Count, fill = Family)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(
    data = n_df_KB,
    aes(x = Date_label, y = 1.05, label = (N_bees)),
    inherit.aes = FALSE) +
  coord_cartesian(ylim = c(0, 1.1)) + 
  labs(y = 'Proportion of pollen', x = 'Date') + 
  theme(axis.text.x = element_text(angle = 45,  vjust = 0.6))
  
pollen_samples %>% 
  filter(Site == 'JAM') %>% 
  ggplot(aes(x = Date_label, y = Count, fill = Family)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(
    data = n_df_JAM,
    aes(x = Date_label, y = 1.05, label = (N_bees)),
    inherit.aes = FALSE) +
  coord_cartesian(ylim = c(0, 1.1)) + 
  labs(y = 'Proportion of pollen', x = 'Date') + 
  theme(axis.text.x = element_text(angle = 45,  vjust = 0.6))





# abundance for 50m
pollen_samples %>% 
  filter(!is.na(Abundance_for50)) %>% 
  group_by(Slide_code) %>% 
  ggplot(aes(x = Abundance_for50)) + 
  geom_histogram(stat='count')

# abundance for 200m
pollen_samples %>% 
  filter(!is.na(Abundance_for200)) %>% 
  group_by(Slide_code) %>% 
  ggplot(aes(x = Abundance_for200)) + 
  geom_histogram(stat='count')


```

```{r Behviour_figures}

# label by week

beehav_full <- beehav_full %>%
  filter(!is.na(Date_beehav)) %>% 
  mutate(Week_index = as.numeric(difftime(floor_date(Date_beehav, "week"),
                                     floor_date(min(Date_beehav), "week"),
                                     units = "weeks") + 1))

# remove duplicates within the same week if there are any by arranging "social" first, then removing dupes
beehav_sum_weekly <- beehav_full %>%
  group_by(Week_index, Nest) %>%
  arrange(desc(Num_females_same_day)) %>%
  slice_head(n = 1) %>% 
  ungroup()


# plot nest socialty throughout the season 

# make sample size for figure
sample_size_beehav_full <- beehav_sum_weekly %>%
  count(Week_index)


# con
beehav_sum_weekly %>%
  ggplot(aes(x = Week_index, fill = Social_status_con)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent") +
  geom_text(data = sample_size_beehav_full,
            aes(x = Week_index, y = 1.05,
                label = paste0(n)),
            inherit.aes = FALSE) +
  scale_fill_manual(values = c("#045b87", "#52c5ff"))



# max number of females in each nest 
# Conservative estimate
beehav_sum %>%
  filter(Num_females_same_day != 0) %>% 
  ggplot(aes(x = Num_females_same_day, fill = Site)) +
  geom_bar(position = 'dodge') +
  scale_fill_manual(values = c("#e65f55", "#edc647"))  +
  labs(y = 'Number of nests', x = 'Number of females')



# Number females over time in social nests conservative estimate
beehav_sum_weekly %>%
  filter(Nest == "J18" | Nest == "J100" | Nest == "J87" | Nest == "J91" | Nest == "J92" | Nest == "K13") %>% 
  ggplot(aes(x = Week_index, y = Num_females_same_day, colour = Nest, fill = Nest)) +
  geom_line() +
  geom_point() +
  ylim(0, 4)


# plot total number of nest sociality
beehav_sum %>%
  filter(Num_females_same_day != 0) %>% 
  ggplot(aes(x = Site, fill = Social_status_con)) +
  geom_bar(position = "stack") +
  scale_fill_manual(values = c("#045b87", "#52c5ff")) +
  labs(fill = "Sociality", y = 'Number of nests')
  



```

```{r Pollen_and_Sociality_figures}

# sample size for conservative
pollen_beehav %>%
  group_by(Social_status_at_time_con) %>%
  summarise(n_samples = n_distinct(Slide_code))


## Violin plots

# richness per nest, compiled
pollen_beehav_nest %>% 
  ggplot(aes(x = Social_status_at_time_con, y = Richness_nest, fill = Social_status_at_time_con )) + 
  geom_violin() + 
  scale_fill_manual(values = c("#045b87", "#52c5ff")) +
  labs(y = "Richness per nest", x = 'Sociality') +
  theme(legend.position = "none")

# richness per invidivual, average
pollen_beehav_ind %>% 
  ggplot(aes(x = Social_status_at_time_con, y = Richness_ind_mean, fill = Social_status_at_time_con )) + 
  geom_violin() + 
  scale_fill_manual(values = c("#045b87", "#52c5ff")) +
  labs(y = "Average richness per individual", x = 'Sociality') +
  theme(legend.position = "none")



# all samples of social nests
pollen_beehav %>% 
  filter(Social_status_at_time_con == "social") %>% 
  ggplot(aes(x = Date_pollen, y = Count, fill = Family)) +
  geom_bar(stat = "identity", position = "fill") +  
  labs(x = "Date", y = "Proportion of pollen", title = "social nests") +
  facet_wrap(~ Bee_ID, scales = "free_x") 

# all samples of solitary nests
pollen_beehav %>% 
  filter(Social_status_at_time_con == "solitary") %>% 
  ggplot(aes(x = Date_pollen, y = Count, fill = Family)) +
  geom_bar(stat = "identity", position = "fill") +  
  labs(x = "Date", y = "Proportion of pollen", title = "solitary nests") +
  facet_wrap(~ Bee_ID, scales = "free_x")


pollen_beehav_ind %>%
  filter(Social_status_at_time_con == 'solitary') %>% 
  ggplot(aes(x = Date_pollen, y = Richness_ind, colour = Bee_ID)) +
  geom_jitter(height = 0, width = 0, alpha = 0.7) + 
  geom_line() +
  theme(legend.position = 'none')

pollen_beehav_ind %>%
  filter(Social_status_at_time_con == 'social') %>% 
  ggplot(aes(x = Date_pollen, y = Richness_ind, colour = Bee_ID)) +
  geom_jitter(height = 0, width = 0, alpha = 0.7) + 
  geom_line() +
  theme(legend.position = 'none')


```
