---
title: "03_Analyses"
format:
  html:
    embed-resources: true
editor: visual
---

```{r Load, include=FALSE}

library(tidyverse)
library(vegan) # for NMDS and diversity 
library(lme4) # for GLMs
library(performance) # for model assumptions 
library(DHARMa)

# pollen data
pollen_samples <- read_csv('Data/Pollen_and_Surveys/Pollen_samples_data_cleaned.csv')

# nest-level data summary
beehav_sum <- read_csv('Data/Behaviour/Behaviour_nest_summary_cleaned.csv')

# nest-level data all social statuses
beehav_full <- read_csv('Data/Behaviour/Behaviour_nest_full_cleaned.csv')

# pollen_samples and behaviour data
pollen_beehav <- read_csv('Data/Behaviour/Pollen_and_behaviour_cleaned.csv')

# abundance data for RDA
rda_abundance_50 <- read_csv('Data/Pollen_and_Surveys/Abundance_50m_cleaned.csv')
rda_abundance_200 <- read_csv('Data/Pollen_and_Surveys/Abundance_200m_cleaned.csv')

# set theme
theme_set(theme_classic(base_size = 15))

```

```{r Sociality, include=FALSE}

table(beehav_sum$Num_females_same_day)
# ignore: 11 nests had 0 observed females partaking in nest care
# 36 had 1 female at a given time partaking in nest care
# 3 nests had 2 females
# 2 nests had 3 females
# 2+3 / 36+2+3 = 12% are social

# mean number of females
beehav_sum %>% filter(Social_status_con == 'social')
# (2 + 2 + 2 + 3 + 3)/ 5  = 2.4

# first social nest
beehav_full %>% filter(Social_status_con == 'social')
# 2024-11-14 

# social nests 
beehav_full %>% filter(Social_status_lib == 'social')

# were these nests just social, or both social and solitary?
beehav_full %>% filter(Nest == 'J100' | Nest == 'J18' | Nest == 'J87' | Nest == 'J91' | Nest == 'J92' | Nest == 'J51' | Nest == 'J75')

# J100: 
 # 2025-01-16 - solitary for 1 day
 # 2025-02-04 - social for 1 day

# J18: 
 # 2024-11-14 to 2024-11-25 - social for 12 days (solitary for one day in between)
 # 2024-12-02 to 2025-01-16 - solitary for 45 days

# J87
 # 2024-12-17 to 2025-01-06 - solitary for 20 days
 # 2025-01-07 - social for 1 day
 # 2025-01-15 to 2025-02-04 - solitary for 20 days

# J91
 # 2025-01-16 to 2025-01-22 - social for 7 days
 # not active in subsequent recordings

# J92
 # 2025-01-16 to 2025-01-28 - social for 13 days

# J56
 # 2025-01-06 - social in liberal estimate
 # 2025-01-16 solitary

# J75
 # 2024-12-02 to 2024-12-05 - social in liberal estimate


```

```{r Flower_Constancy}

### 2i. Flower constancy

# how many samples are above 95% of one pollen type
pollen_samples %>% 
  filter(Count_scaled >= 285) %>% 
  summarise(count = length(unique(Slide_code)))
# 46 out of 83 samples = 55%


```

```{r Pollen_Composition_NMDS}

### 2ii. Pollen composition comparison within and between individuals

# take bees caught more than once
# pollen_samples_xs <- pollen_samples %>% filter(Num_of_samples > 1)


# take pollen types that occur in more than one sample
pollen_samples_xs <- pollen_samples %>%
  group_by(Family) %>%
  filter(n_distinct(Slide_code) > 3) %>%
  ungroup()

# make sure the sum of pollen counts is 300
pollen_samples_xs <- pollen_samples_xs %>%
  group_by(Slide_code) %>%
  filter(sum(Count_scaled) == 300) %>%
  ungroup()

length(unique(pollen_samples_xs$Bee_ID)) # 22
length(unique(pollen_samples_xs$Slide_code)) # 42

# pivot wider
pollen_samples_wide_xs <- pollen_samples_xs %>% select(Bee_ID, Slide_code, Date_pollen, Family, Count_scaled)
pollen_samples_wide_xs <- pivot_wider(pollen_samples_wide_xs, names_from = 'Family', values_from = 'Count_scaled', id_cols = c(Bee_ID, Slide_code, Date_pollen))

# replace NA with 0
pollen_samples_wide_xs[is.na(pollen_samples_wide_xs)] <- 0

# extract descriptors for merging later
desc <- pollen_samples_wide_xs %>% select(Bee_ID, Slide_code, Date_pollen)

# take bees caught more than once again
pollen_samples_wide_xs <- pollen_samples_wide_xs %>%
  group_by(Bee_ID) %>%
  filter(n() > 1)

length(unique(pollen_samples_wide_xs$Bee_ID)) # 15 / 49
length(unique(pollen_samples_wide_xs$Slide_code)) # 35 / 83


## Create NMDS

nmds_pollen_comp <- metaMDS(pollen_samples_wide_xs[4:ncol(pollen_samples_wide_xs)], distance = 'bray', k = 2)

# inspect

print(nmds_pollen_comp) # stress is small but fine
stressplot(nmds_pollen_comp) # should look like stairs

plot(nmds_pollen_comp)
scores(nmds_pollen_comp)

# extract NMDS scores for bees 
nmds_sample_scores <- as.data.frame(scores(nmds_pollen_comp, display = "sites"))
  
# missing columns I want
nmds_sample_scores$Slide_code <- pollen_samples_wide_xs$Slide_code
nmds_sample_scores <- left_join(nmds_sample_scores, desc)
  

# Plot 

# hulls (≥3 points)
hulls <- nmds_sample_scores %>%
  group_by(Bee_ID) %>%
  filter(n() >= 3) %>%
  slice(chull(NMDS1, NMDS2))

# lines (exactly 2 points)
lines2 <- nmds_sample_scores %>%
  group_by(Bee_ID) %>%
  filter(n() == 2)

ggplot(nmds_sample_scores) + 
  geom_polygon(data = hulls,
               aes(NMDS1, NMDS2, group = Bee_ID, fill = Bee_ID),
               alpha = 0.2) +
  geom_line(data = lines2,
            aes(NMDS1, NMDS2, group = Bee_ID, colour = Bee_ID),
            linewidth = 0.6, alpha=0.4) +
  geom_point(aes(NMDS1, NMDS2, colour = Bee_ID, alpha = 0.6), size = 2) +
  theme(legend.position = "none")



# checking the duplicates

# # round to 6 decimals
# nmds_sample_scores$NMDS1 <- round(nmds_sample_scores$NMDS1, 6)
# nmds_sample_scores$NMDS2 <- round(nmds_sample_scores$NMDS2, 6)
# 
# # show duplicated values
# dupe_1 <- nmds_sample_scores %>%
#   group_by(NMDS1) %>%
#   filter(n() > 1)
# dupe_2 <- nmds_sample_scores %>%
#   group_by(NMDS2) %>%
#   filter(n() > 1)
# 
# dupe_1_full <- inner_join(dupe_1, pollen_samples_wide_xs)
# dupe_2_full <- inner_join(dupe_2, pollen_samples_wide_xs)



# how many bees and samples?

length(unique(nmds_sample_scores$Bee_ID))
length(unique(nmds_sample_scores$Slide_code))


```

```{r Pollen_Diversity_and_Richness, include=FALSE}


### 2iii. Pollen collection divserity 

# plot richness over time

# bees with 2 samples
pollen_samples %>%
  filter(Num_of_samples == 2) %>% 
  ggplot(aes(x = Day_of_season, y = Num_of_subtypes, colour = Bee_ID)) +
  geom_jitter(height = 0.05, width = 0.3, alpha = 0.7) + 
  geom_line()

# bees with >2 samples
pollen_samples %>%
  filter(Num_of_samples > 2) %>% 
  ggplot(aes(x = Day_of_season, y = Num_of_subtypes, colour = Bee_ID)) +
  geom_jitter(height = 0.05, width = 0.3, alpha = 0.7) + 
  geom_line()

# bees with 1 sample
pollen_samples %>%
  filter(Num_of_samples == 1) %>% 
  ggplot(aes(x = Day_of_season, y = Num_of_subtypes, colour = Bee_ID)) +
  geom_jitter(height = 0.05, width = 0.3, alpha = 0.7) 




```

```{r Floral_Abundance_RDA}


### 2iv. Floral abundance


# remove NAs from the unknown pollen types no abundance data for unknowns)
pollen_samples_known <- pollen_samples %>% filter(!is.na(Abundance_for50))

# # plot 50m
# pollen_samples_known %>% 
#   ggplot(aes(Abundance_for50, Count_scaled, colour = Subtype)) +
#   geom_jitter(alpha = 0.6, height = 0.2, width = 0)
# 
# # plot 200m
# pollen_samples_known %>% 
#   ggplot(aes(Abundance_for200, Count_scaled, colour = Subtype)) +
#   geom_jitter(alpha = 0.6, height = 0.2, width = 0)

# take pollen types that occur in at least 3 samples
pollen_samples_known <- pollen_samples_known %>%
  group_by(Family) %>%
  filter(n_distinct(Slide_code) > 2) %>%
  ungroup()

# how many grains left in the samples?
pollen_samples_known %>%
  group_by(Slide_code) %>%
  summarise(count = sum(Count_scaled))
# a few with less than 200 or even 100, so remove those because they make inflate that plants importance

# make sure the sum of pollen counts is at least 200
pollen_samples_known <- pollen_samples_known %>%
  group_by(Slide_code) %>%
  filter(sum(Count_scaled) >= 200) %>%
  ungroup()

# sample size
length(unique(pollen_samples_known$Bee_ID)) # 39 / 49
length(unique(pollen_samples_known$Slide_code)) # 65 / 83

# Data for pollen samples
# take columns
pollen_samples_known_wide <- pollen_samples_known %>% select(Num_ID, Slide_code, Site, Season, Family, Count_scaled)
# pivot wider
pollen_samples_known_wide <- pivot_wider(pollen_samples_known_wide, names_from = 'Family', values_from = 'Count_scaled', id_cols = c(Num_ID, Slide_code, Site, Season))
# replace NA with 0
pollen_samples_known_wide[is.na(pollen_samples_known_wide)] <- 0

# make Bee_ID it's own thing
Num_ID <- pollen_samples_known_wide$Num_ID


# remove those same ones from abundance df
rda_abundance_50 <- rda_abundance_50 %>%
  filter(Slide_code %in% pollen_samples_known_wide$Slide_code)
rda_abundance_200 <- rda_abundance_200 %>%
  filter(Slide_code %in% pollen_samples_known_wide$Slide_code)

# arrange by ID 
pollen_samples_known_wide <- pollen_samples_known_wide %>% arrange(Num_ID)
rda_abundance_50 <- rda_abundance_50 %>% arrange(Num_ID)
rda_abundance_200 <- rda_abundance_200 %>% arrange(Num_ID)


# Old incorrect way
# # Data for 50m abundance
# # take columns 
# abundance_wide_50 <- pollen_samples_known %>% select(Slide_code, Family, Abundance_for50)
# # pivot wider
# abundance_wide_50 <- pivot_wider(abundance_wide_50, names_from = 'Family', values_from = 'Abundance_for50', id_cols = Slide_code)
# # replace NA with 0
# abundance_wide_50[is.na(abundance_wide_50)] <- 0
# 
# # Data for 200m abundance
# # take columns 
# abundance_wide_200 <- pollen_samples_known %>% select(Slide_code, Family, Abundance_for200)
# # pivot wider
# abundance_wide_200 <- pivot_wider(abundance_wide_200, names_from = 'Family', values_from = 'Abundance_for200', id_cols = Slide_code)
# # replace NA with 0
# abundance_wide_200[is.na(abundance_wide_200)] <- 0

# # make abundance numerical (other columns required before)
# abundance_wide_50 <- abundance_wide_50 %>% select(-Slide_code)
# abundance_wide_200 <- abundance_wide_200 %>% select(-Slide_code)


# make samples numerical (other columns required before)
pollen_samples_known_wide_num <- pollen_samples_known_wide %>% select(-Num_ID, -Slide_code, -Site, -Season)
rda_abundance_50 <- rda_abundance_50 %>% select(-Slide_code, -Num_ID, -Site, -Season)
rda_abundance_50 <- rda_abundance_50 %>% select(-...1)
rda_abundance_200 <- rda_abundance_200 %>% select(-Slide_code, -Num_ID, -Site, -Season)
rda_abundance_200 <- rda_abundance_200 %>% select(-...1)



# filter out columns with over 50% zeros
rda_abundance_50_filt <- rda_abundance_50 %>%
  select(where(~ mean(. == 0, na.rm = TRUE) < 0.5))
# filter out columns with over 50% zeros
rda_abundance_200_filt <- rda_abundance_200 %>%
  select(where(~ mean(. == 0, na.rm = TRUE) < 0.5))


## RDA for 50m

rda_50 <- cca(pollen_samples_known_wide_num ~ . + Condition(Num_ID),
           data = rda_abundance_50_filt)

plot(rda_50) 

summary(rda_50) 


## RDA for 200m

rda_200 <- cca(pollen_samples_known_wide_num ~ . + Condition(Num_ID),
           data = rda_abundance_200_filt)

plot(rda_200)

summary(rda_200)



## Plot 

# plot only certain bees, e.g., flower constant samples 
# 
# # paste abundance to names
# names(abundance_wide_50)[2:9] <- paste0("Abundance_", names(abundance_wide_50)[2:9])
#   
# # add abundance 
# flow_con_x <- left_join(pollen_samples_known_wide, abundance_wide_50, by = 'Slide_code')
# 
# # take flower constant samples 
# flow_con_x <- flow_con_x %>% filter(Plantaginaceae >= 285)
# 
# abundance_wide_50 %>%
#  filter(Slide_code %in% c(flow_con_x$Slide_code))


# colour
library(paletteer)
one <- paletteer_d("ggthemes::Tableau_20")
two <- paletteer_d("ggthemes::manyeys")
three <- paletteer_dynamic("cartography::pink.pal", 20)

pal <- rbind(one, two, three)

cols <- as.factor(pollen_samples_known_wide$Num_ID)
# pal <- grDevices::hcl.colors(nlevels(cols), palette = "Set 2")
col_map <- setNames(pal, levels(cols))
bp <- scores(rda, display = "bp")


# Save fig I
 jpeg(file.path(('Figures/'), "RDA_50m.jpg"),
      width = 4600, height = 3500, res = 500)


## 50 m ##

plot(rda_50, type = "n")
points(rda_50, display = "sites", col = cols, pch = 16)
text(rda_50, display = "sites",
     labels = pollen_samples_known_wide$Num_ID,
     cex = 0.7, # size of bee ID label
     pos = 3, offset = 0.3) # above
points(rda_50, display = "sites", 
       col = col_map[cols], 
       pch = 16)
arrows(0, 0,
       scores(rda_50, display = "bp")[,1],
       scores(rda_50, display = "bp")[,2],
       col = "black",
       length = 0.001) # size of arrow head in the middle 
text(rda_50, display = "bp",
     col = "black", cex = 0.8) # size of text


# Save fig II
 dev.off()

 
# # Save fig I
#  jpeg(file.path(('Figures/'), "RDA_200m.jpg"),
#       width = 4600, height = 3500, res = 500)
#  
#  
# ## 200 m ##
# 
# plot(rda_200, type = "n")
# points(rda_200, display = "sites", col = cols, pch = 16)
# text(rda_200, display = "sites", # bee ID labels
#      labels = pollen_samples_known_wide$Num_ID,
#      cex = 0.6, # size of bee ID label
#      pos = 3, offset = 0.3, # above dot
#      col = "grey30") 
# points(rda_200, display = "sites", 
#        col = col_map[cols], 
#        pch = 16)
# arrows(0, 0,
#        scores(rda_200, display = "bp")[,1],
#        scores(rda_200, display = "bp")[,2],
#        col = "black",
#        length = 0.001) # size of arrow head in the middle 
# text(rda_200, display = "bp",
#      col = "black", cex = 0.8) # size of text
# 
# # Save fig II
#  dev.off()
 

```

```{r Pollen_and_Sociality}

### 3i. FLower constancy and social status

# total counts 
pollen_beehav %>% 
  group_by(Social_status_at_time_con) %>% 
  summarise(Count = (length(unique(Slide_code))))
# 11 social and 34 solitary samples
# flower constant counts
pollen_beehav %>% 
  filter(Count_scaled >= 285) %>% 
  count(Social_status_at_time_con)
# 6 social and 20 solitary
# 55% social and 59% solitary sampels were flower constant (of bees that we have both pollen samples and social statuses for)


# total counts 
pollen_beehav %>% 
  group_by(Social_status_at_time_lib) %>% 
  summarise(Count = (length(unique(Slide_code))))
# 12 social, 33 solitary
pollen_beehav %>% 
  filter(Count_scaled >= 285) %>% 
  count(Social_status_at_time_lib)
# 7 social, 19 solitary for liberal estimate 
# 58% and 58%




### 3ii. Pollen diversity and sociality 



## Diversity 
# # pivot wider
# pollen_beehav_wide <- pivot_wider(pollen_beehav_wide, names_from = 'Subtype', values_from = 'Count_scaled', id_cols = c(Bee_ID, Slide_code, Date_pollen))
# 
# # replace NA with 0
# pollen_beehav_wide[is.na(pollen_beehav_wide)] <- 0
# 
# # take just the samples and calculate diversity
# just_pollen_beehav <- pollen_beehav_wide %>% select(-Slide_code, -Bee_ID, -Date_pollen)
# diversity_beehav <- just_pollen_beehav %>% diversity(index = "shannon")
# # the zeros are flower constant bees
# 
# # make df and rename with capital
# diversity_beehav <- as.data.frame(diversity_beehav)
# diversity_beehav <- diversity_beehav %>% rename(Diversity = diversity_beehav)
# 
# # add the descriptive info back in
# diversity_beehav$Slide_code <- pollen_beehav_wide$Slide_code
# diversity_beehav$Bee_ID <- pollen_beehav_wide$Bee_ID
# to_join_beehav <- pollen_beehav %>% select(-...1, -Family, -Subtype, -Count, -Count_scaled)
# to_join_beehav <- distinct(to_join_beehav)
# pollen_diversity_beehav <- inner_join(to_join_beehav, diversity_beehav)

# create day of season, better than date for model
# pollen_beehav_xs <- pollen_beehav_xs %>%
#  mutate(Day_of_season = as.integer(Date_pollen - season_start) + 1)
# move earlier
# pollen_diversity_beehav <- pollen_diversity_beehav %>% relocate(Day_of_season, .after = 5)







```
